<?php
/**
 * LoginApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth-Service API Help
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\Auth\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exos\Auth\ApiException;
use Exos\Auth\Configuration;
use Exos\Auth\FormDataProcessor;
use Exos\Auth\HeaderSelector;
use Exos\Auth\ObjectSerializer;

/**
 * LoginApi Class Doc Comment
 *
 * @category Class
 * @package  Exos\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LoginApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'loginApiV1Login' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'loginApiV1LoginIdentityProviders' => [
            'application/json',
        ],
        'loginApiV1LoginTenants' => [
            'application/json',
        ],
        'loginApiV1LoginWebapps' => [
            'application/json',
        ],
        'loginApiV1LoginWindows' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'loginApiV1LoginWithPasswordChange' => [
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation loginApiV1Login
     *
     * Allows to perform a login via user name and password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginUsernamePasswordRequest|null $kaba_exos_auth_service_areas_api_models_login_username_password_request kaba_exos_auth_service_areas_api_models_login_username_password_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1Login'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails|\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails
     */
    public function loginApiV1Login($kaba_exos_auth_service_areas_api_models_login_username_password_request = null, string $contentType = self::contentTypes['loginApiV1Login'][0])
    {
        list($response) = $this->loginApiV1LoginWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_username_password_request, $contentType);
        return $response;
    }

    /**
     * Operation loginApiV1LoginWithHttpInfo
     *
     * Allows to perform a login via user name and password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginUsernamePasswordRequest|null $kaba_exos_auth_service_areas_api_models_login_username_password_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1Login'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails|\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function loginApiV1LoginWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_username_password_request = null, string $contentType = self::contentTypes['loginApiV1Login'][0])
    {
        $request = $this->loginApiV1LoginRequest($kaba_exos_auth_service_areas_api_models_login_username_password_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginApiV1LoginAsync
     *
     * Allows to perform a login via user name and password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginUsernamePasswordRequest|null $kaba_exos_auth_service_areas_api_models_login_username_password_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1Login'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginAsync($kaba_exos_auth_service_areas_api_models_login_username_password_request = null, string $contentType = self::contentTypes['loginApiV1Login'][0])
    {
        return $this->loginApiV1LoginAsyncWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_username_password_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginApiV1LoginAsyncWithHttpInfo
     *
     * Allows to perform a login via user name and password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginUsernamePasswordRequest|null $kaba_exos_auth_service_areas_api_models_login_username_password_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1Login'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginAsyncWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_username_password_request = null, string $contentType = self::contentTypes['loginApiV1Login'][0])
    {
        $returnType = 'string';
        $request = $this->loginApiV1LoginRequest($kaba_exos_auth_service_areas_api_models_login_username_password_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'loginApiV1Login'
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginUsernamePasswordRequest|null $kaba_exos_auth_service_areas_api_models_login_username_password_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1Login'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loginApiV1LoginRequest($kaba_exos_auth_service_areas_api_models_login_username_password_request = null, string $contentType = self::contentTypes['loginApiV1Login'][0])
    {



        $resourcePath = '/api/v1/Login';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($kaba_exos_auth_service_areas_api_models_login_username_password_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($kaba_exos_auth_service_areas_api_models_login_username_password_request));
            } else {
                $httpBody = $kaba_exos_auth_service_areas_api_models_login_username_password_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation loginApiV1LoginIdentityProviders
     *
     * Returns a list of all external identity providers (openIdConnect)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginIdentityProviders'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsIdentityProviderModel[]
     */
    public function loginApiV1LoginIdentityProviders(string $contentType = self::contentTypes['loginApiV1LoginIdentityProviders'][0])
    {
        list($response) = $this->loginApiV1LoginIdentityProvidersWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation loginApiV1LoginIdentityProvidersWithHttpInfo
     *
     * Returns a list of all external identity providers (openIdConnect)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginIdentityProviders'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsIdentityProviderModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function loginApiV1LoginIdentityProvidersWithHttpInfo(string $contentType = self::contentTypes['loginApiV1LoginIdentityProviders'][0])
    {
        $request = $this->loginApiV1LoginIdentityProvidersRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsIdentityProviderModel[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsIdentityProviderModel[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsIdentityProviderModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginApiV1LoginIdentityProvidersAsync
     *
     * Returns a list of all external identity providers (openIdConnect)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginIdentityProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginIdentityProvidersAsync(string $contentType = self::contentTypes['loginApiV1LoginIdentityProviders'][0])
    {
        return $this->loginApiV1LoginIdentityProvidersAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginApiV1LoginIdentityProvidersAsyncWithHttpInfo
     *
     * Returns a list of all external identity providers (openIdConnect)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginIdentityProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginIdentityProvidersAsyncWithHttpInfo(string $contentType = self::contentTypes['loginApiV1LoginIdentityProviders'][0])
    {
        $returnType = '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsIdentityProviderModel[]';
        $request = $this->loginApiV1LoginIdentityProvidersRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'loginApiV1LoginIdentityProviders'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginIdentityProviders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loginApiV1LoginIdentityProvidersRequest(string $contentType = self::contentTypes['loginApiV1LoginIdentityProviders'][0])
    {


        $resourcePath = '/api/v1/Login/identityProviders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation loginApiV1LoginTenants
     *
     * Returns a list of all available tenants/clients (not to be confused with OAuth client id)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginTenants'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsTenantModel[]
     */
    public function loginApiV1LoginTenants(string $contentType = self::contentTypes['loginApiV1LoginTenants'][0])
    {
        list($response) = $this->loginApiV1LoginTenantsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation loginApiV1LoginTenantsWithHttpInfo
     *
     * Returns a list of all available tenants/clients (not to be confused with OAuth client id)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginTenants'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsTenantModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function loginApiV1LoginTenantsWithHttpInfo(string $contentType = self::contentTypes['loginApiV1LoginTenants'][0])
    {
        $request = $this->loginApiV1LoginTenantsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsTenantModel[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsTenantModel[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsTenantModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginApiV1LoginTenantsAsync
     *
     * Returns a list of all available tenants/clients (not to be confused with OAuth client id)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginTenants'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginTenantsAsync(string $contentType = self::contentTypes['loginApiV1LoginTenants'][0])
    {
        return $this->loginApiV1LoginTenantsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginApiV1LoginTenantsAsyncWithHttpInfo
     *
     * Returns a list of all available tenants/clients (not to be confused with OAuth client id)
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginTenants'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginTenantsAsyncWithHttpInfo(string $contentType = self::contentTypes['loginApiV1LoginTenants'][0])
    {
        $returnType = '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsTenantModel[]';
        $request = $this->loginApiV1LoginTenantsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'loginApiV1LoginTenants'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginTenants'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loginApiV1LoginTenantsRequest(string $contentType = self::contentTypes['loginApiV1LoginTenants'][0])
    {


        $resourcePath = '/api/v1/Login/tenants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation loginApiV1LoginWebapps
     *
     * Deprecated: returns a list of all available webapps/client applications. Please use \&quot;/v1.0/application/webapplications\&quot; of ExosApi as this endpoint will be removed in the future
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWebapps'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsWebAppModel[]
     * @deprecated
     */
    public function loginApiV1LoginWebapps(string $contentType = self::contentTypes['loginApiV1LoginWebapps'][0])
    {
        list($response) = $this->loginApiV1LoginWebappsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation loginApiV1LoginWebappsWithHttpInfo
     *
     * Deprecated: returns a list of all available webapps/client applications. Please use \&quot;/v1.0/application/webapplications\&quot; of ExosApi as this endpoint will be removed in the future
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWebapps'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsWebAppModel[], HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function loginApiV1LoginWebappsWithHttpInfo(string $contentType = self::contentTypes['loginApiV1LoginWebapps'][0])
    {
        $request = $this->loginApiV1LoginWebappsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsWebAppModel[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsWebAppModel[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsWebAppModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginApiV1LoginWebappsAsync
     *
     * Deprecated: returns a list of all available webapps/client applications. Please use \&quot;/v1.0/application/webapplications\&quot; of ExosApi as this endpoint will be removed in the future
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWebapps'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function loginApiV1LoginWebappsAsync(string $contentType = self::contentTypes['loginApiV1LoginWebapps'][0])
    {
        return $this->loginApiV1LoginWebappsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginApiV1LoginWebappsAsyncWithHttpInfo
     *
     * Deprecated: returns a list of all available webapps/client applications. Please use \&quot;/v1.0/application/webapplications\&quot; of ExosApi as this endpoint will be removed in the future
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWebapps'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function loginApiV1LoginWebappsAsyncWithHttpInfo(string $contentType = self::contentTypes['loginApiV1LoginWebapps'][0])
    {
        $returnType = '\Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsWebAppModel[]';
        $request = $this->loginApiV1LoginWebappsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'loginApiV1LoginWebapps'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWebapps'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function loginApiV1LoginWebappsRequest(string $contentType = self::contentTypes['loginApiV1LoginWebapps'][0])
    {


        $resourcePath = '/api/v1/Login/webapps';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation loginApiV1LoginWindows
     *
     * Allows to perform a windows login. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginRequest|null $kaba_exos_auth_service_areas_api_models_login_request kaba_exos_auth_service_areas_api_models_login_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWindows'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function loginApiV1LoginWindows($kaba_exos_auth_service_areas_api_models_login_request = null, string $contentType = self::contentTypes['loginApiV1LoginWindows'][0])
    {
        list($response) = $this->loginApiV1LoginWindowsWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_request, $contentType);
        return $response;
    }

    /**
     * Operation loginApiV1LoginWindowsWithHttpInfo
     *
     * Allows to perform a windows login. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginRequest|null $kaba_exos_auth_service_areas_api_models_login_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWindows'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function loginApiV1LoginWindowsWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_request = null, string $contentType = self::contentTypes['loginApiV1LoginWindows'][0])
    {
        $request = $this->loginApiV1LoginWindowsRequest($kaba_exos_auth_service_areas_api_models_login_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginApiV1LoginWindowsAsync
     *
     * Allows to perform a windows login. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginRequest|null $kaba_exos_auth_service_areas_api_models_login_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWindows'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginWindowsAsync($kaba_exos_auth_service_areas_api_models_login_request = null, string $contentType = self::contentTypes['loginApiV1LoginWindows'][0])
    {
        return $this->loginApiV1LoginWindowsAsyncWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginApiV1LoginWindowsAsyncWithHttpInfo
     *
     * Allows to perform a windows login. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginRequest|null $kaba_exos_auth_service_areas_api_models_login_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWindows'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginWindowsAsyncWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_request = null, string $contentType = self::contentTypes['loginApiV1LoginWindows'][0])
    {
        $returnType = 'string';
        $request = $this->loginApiV1LoginWindowsRequest($kaba_exos_auth_service_areas_api_models_login_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'loginApiV1LoginWindows'
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginRequest|null $kaba_exos_auth_service_areas_api_models_login_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWindows'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loginApiV1LoginWindowsRequest($kaba_exos_auth_service_areas_api_models_login_request = null, string $contentType = self::contentTypes['loginApiV1LoginWindows'][0])
    {



        $resourcePath = '/api/v1/Login/Windows';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($kaba_exos_auth_service_areas_api_models_login_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($kaba_exos_auth_service_areas_api_models_login_request));
            } else {
                $httpBody = $kaba_exos_auth_service_areas_api_models_login_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation loginApiV1LoginWithPasswordChange
     *
     * Allows to perform a login with an integrated password change with user name, password and new password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginWithPasswordChangeRequest|null $kaba_exos_auth_service_areas_api_models_login_with_password_change_request kaba_exos_auth_service_areas_api_models_login_with_password_change_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWithPasswordChange'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails
     */
    public function loginApiV1LoginWithPasswordChange($kaba_exos_auth_service_areas_api_models_login_with_password_change_request = null, string $contentType = self::contentTypes['loginApiV1LoginWithPasswordChange'][0])
    {
        list($response) = $this->loginApiV1LoginWithPasswordChangeWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_with_password_change_request, $contentType);
        return $response;
    }

    /**
     * Operation loginApiV1LoginWithPasswordChangeWithHttpInfo
     *
     * Allows to perform a login with an integrated password change with user name, password and new password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginWithPasswordChangeRequest|null $kaba_exos_auth_service_areas_api_models_login_with_password_change_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWithPasswordChange'] to see the possible values for this operation
     *
     * @throws \Exos\Auth\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function loginApiV1LoginWithPasswordChangeWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_with_password_change_request = null, string $contentType = self::contentTypes['loginApiV1LoginWithPasswordChange'][0])
    {
        $request = $this->loginApiV1LoginWithPasswordChangeRequest($kaba_exos_auth_service_areas_api_models_login_with_password_change_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'string',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\Auth\Model\MicrosoftAspNetCoreMvcProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation loginApiV1LoginWithPasswordChangeAsync
     *
     * Allows to perform a login with an integrated password change with user name, password and new password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginWithPasswordChangeRequest|null $kaba_exos_auth_service_areas_api_models_login_with_password_change_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWithPasswordChange'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginWithPasswordChangeAsync($kaba_exos_auth_service_areas_api_models_login_with_password_change_request = null, string $contentType = self::contentTypes['loginApiV1LoginWithPasswordChange'][0])
    {
        return $this->loginApiV1LoginWithPasswordChangeAsyncWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_with_password_change_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation loginApiV1LoginWithPasswordChangeAsyncWithHttpInfo
     *
     * Allows to perform a login with an integrated password change with user name, password and new password. If successful, returns a identity token.
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginWithPasswordChangeRequest|null $kaba_exos_auth_service_areas_api_models_login_with_password_change_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWithPasswordChange'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function loginApiV1LoginWithPasswordChangeAsyncWithHttpInfo($kaba_exos_auth_service_areas_api_models_login_with_password_change_request = null, string $contentType = self::contentTypes['loginApiV1LoginWithPasswordChange'][0])
    {
        $returnType = 'string';
        $request = $this->loginApiV1LoginWithPasswordChangeRequest($kaba_exos_auth_service_areas_api_models_login_with_password_change_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'loginApiV1LoginWithPasswordChange'
     *
     * @param  \Exos\Auth\Model\KabaExosAuthServiceAreasApiModelsLoginWithPasswordChangeRequest|null $kaba_exos_auth_service_areas_api_models_login_with_password_change_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['loginApiV1LoginWithPasswordChange'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function loginApiV1LoginWithPasswordChangeRequest($kaba_exos_auth_service_areas_api_models_login_with_password_change_request = null, string $contentType = self::contentTypes['loginApiV1LoginWithPasswordChange'][0])
    {



        $resourcePath = '/api/v1/Login/WithPasswordChange';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($kaba_exos_auth_service_areas_api_models_login_with_password_change_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($kaba_exos_auth_service_areas_api_models_login_with_password_change_request));
            } else {
                $httpBody = $kaba_exos_auth_service_areas_api_models_login_with_password_change_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
