<?php
/**
 * AuditLogApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exos\ExosApi\ApiException;
use Exos\ExosApi\Configuration;
use Exos\ExosApi\FormDataProcessor;
use Exos\ExosApi\HeaderSelector;
use Exos\ExosApi\ObjectSerializer;

/**
 * AuditLogApi Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditLogApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v10AuditLogEntriesAuditLogEventTypesGet' => [
            'application/json',
        ],
        'v10AuditLogEntriesGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v10AuditLogEntriesAuditLogEventTypesGet
     *
     * Get audit event type info
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'] to see the possible values for this operation
     *
     * @throws \Exos\ExosApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Exos\ExosApi\Model\GetAuditLogEventTypeOutputWithTime
     */
    public function v10AuditLogEntriesAuditLogEventTypesGet(string $contentType = self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'][0])
    {
        list($response) = $this->v10AuditLogEntriesAuditLogEventTypesGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation v10AuditLogEntriesAuditLogEventTypesGetWithHttpInfo
     *
     * Get audit event type info
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'] to see the possible values for this operation
     *
     * @throws \Exos\ExosApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Exos\ExosApi\Model\GetAuditLogEventTypeOutputWithTime, HTTP status code, HTTP response headers (array of strings)
     */
    public function v10AuditLogEntriesAuditLogEventTypesGetWithHttpInfo(string $contentType = self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'][0])
    {
        $request = $this->v10AuditLogEntriesAuditLogEventTypesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Exos\ExosApi\Model\GetAuditLogEventTypeOutputWithTime',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Exos\ExosApi\Model\GetAuditLogEventTypeOutputWithTime',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\ExosApi\Model\GetAuditLogEventTypeOutputWithTime',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v10AuditLogEntriesAuditLogEventTypesGetAsync
     *
     * Get audit event type info
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v10AuditLogEntriesAuditLogEventTypesGetAsync(string $contentType = self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'][0])
    {
        return $this->v10AuditLogEntriesAuditLogEventTypesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v10AuditLogEntriesAuditLogEventTypesGetAsyncWithHttpInfo
     *
     * Get audit event type info
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v10AuditLogEntriesAuditLogEventTypesGetAsyncWithHttpInfo(string $contentType = self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'][0])
    {
        $returnType = '\Exos\ExosApi\Model\GetAuditLogEventTypeOutputWithTime';
        $request = $this->v10AuditLogEntriesAuditLogEventTypesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v10AuditLogEntriesAuditLogEventTypesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v10AuditLogEntriesAuditLogEventTypesGetRequest(string $contentType = self::contentTypes['v10AuditLogEntriesAuditLogEventTypesGet'][0])
    {


        $resourcePath = '/v1.0/auditLogEntries/auditLogEventTypes';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v10AuditLogEntriesGet
     *
     * Get audit log entries by odata query options
     *
     * @param  string|null $expand  (optional)
     * @param  string|null $filter LogDate ge 2016-12-31 (optional)
     * @param  string|null $search_string Fulltext search on all string, int and date fields that are selected with $select and $expand. (optional)
     * @param  bool|null $count adds total possible results to the response (optional, default to true)
     * @param  string|null $orderby LogDate desc (optional, default to 'LogDate desc')
     * @param  string|null $select NewValue (optional)
     * @param  int|null $skip skips the first x entries of the response(paging) (optional)
     * @param  int|null $top limits the number of returned records. (optional, default to 1000)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesGet'] to see the possible values for this operation
     *
     * @throws \Exos\ExosApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Exos\ExosApi\Model\GetAuditLogEntriesOutput
     * @deprecated
     */
    public function v10AuditLogEntriesGet($expand = null, $filter = null, $search_string = null, $count = true, $orderby = 'LogDate desc', $select = null, $skip = null, $top = 1000, string $contentType = self::contentTypes['v10AuditLogEntriesGet'][0])
    {
        list($response) = $this->v10AuditLogEntriesGetWithHttpInfo($expand, $filter, $search_string, $count, $orderby, $select, $skip, $top, $contentType);
        return $response;
    }

    /**
     * Operation v10AuditLogEntriesGetWithHttpInfo
     *
     * Get audit log entries by odata query options
     *
     * @param  string|null $expand  (optional)
     * @param  string|null $filter LogDate ge 2016-12-31 (optional)
     * @param  string|null $search_string Fulltext search on all string, int and date fields that are selected with $select and $expand. (optional)
     * @param  bool|null $count adds total possible results to the response (optional, default to true)
     * @param  string|null $orderby LogDate desc (optional, default to 'LogDate desc')
     * @param  string|null $select NewValue (optional)
     * @param  int|null $skip skips the first x entries of the response(paging) (optional)
     * @param  int|null $top limits the number of returned records. (optional, default to 1000)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesGet'] to see the possible values for this operation
     *
     * @throws \Exos\ExosApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Exos\ExosApi\Model\GetAuditLogEntriesOutput, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function v10AuditLogEntriesGetWithHttpInfo($expand = null, $filter = null, $search_string = null, $count = true, $orderby = 'LogDate desc', $select = null, $skip = null, $top = 1000, string $contentType = self::contentTypes['v10AuditLogEntriesGet'][0])
    {
        $request = $this->v10AuditLogEntriesGetRequest($expand, $filter, $search_string, $count, $orderby, $select, $skip, $top, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Exos\ExosApi\Model\GetAuditLogEntriesOutput',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Exos\ExosApi\Model\GetAuditLogEntriesOutput',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Exos\ExosApi\Model\GetAuditLogEntriesOutput',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v10AuditLogEntriesGetAsync
     *
     * Get audit log entries by odata query options
     *
     * @param  string|null $expand  (optional)
     * @param  string|null $filter LogDate ge 2016-12-31 (optional)
     * @param  string|null $search_string Fulltext search on all string, int and date fields that are selected with $select and $expand. (optional)
     * @param  bool|null $count adds total possible results to the response (optional, default to true)
     * @param  string|null $orderby LogDate desc (optional, default to 'LogDate desc')
     * @param  string|null $select NewValue (optional)
     * @param  int|null $skip skips the first x entries of the response(paging) (optional)
     * @param  int|null $top limits the number of returned records. (optional, default to 1000)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function v10AuditLogEntriesGetAsync($expand = null, $filter = null, $search_string = null, $count = true, $orderby = 'LogDate desc', $select = null, $skip = null, $top = 1000, string $contentType = self::contentTypes['v10AuditLogEntriesGet'][0])
    {
        return $this->v10AuditLogEntriesGetAsyncWithHttpInfo($expand, $filter, $search_string, $count, $orderby, $select, $skip, $top, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v10AuditLogEntriesGetAsyncWithHttpInfo
     *
     * Get audit log entries by odata query options
     *
     * @param  string|null $expand  (optional)
     * @param  string|null $filter LogDate ge 2016-12-31 (optional)
     * @param  string|null $search_string Fulltext search on all string, int and date fields that are selected with $select and $expand. (optional)
     * @param  bool|null $count adds total possible results to the response (optional, default to true)
     * @param  string|null $orderby LogDate desc (optional, default to 'LogDate desc')
     * @param  string|null $select NewValue (optional)
     * @param  int|null $skip skips the first x entries of the response(paging) (optional)
     * @param  int|null $top limits the number of returned records. (optional, default to 1000)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function v10AuditLogEntriesGetAsyncWithHttpInfo($expand = null, $filter = null, $search_string = null, $count = true, $orderby = 'LogDate desc', $select = null, $skip = null, $top = 1000, string $contentType = self::contentTypes['v10AuditLogEntriesGet'][0])
    {
        $returnType = '\Exos\ExosApi\Model\GetAuditLogEntriesOutput';
        $request = $this->v10AuditLogEntriesGetRequest($expand, $filter, $search_string, $count, $orderby, $select, $skip, $top, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v10AuditLogEntriesGet'
     *
     * @param  string|null $expand  (optional)
     * @param  string|null $filter LogDate ge 2016-12-31 (optional)
     * @param  string|null $search_string Fulltext search on all string, int and date fields that are selected with $select and $expand. (optional)
     * @param  bool|null $count adds total possible results to the response (optional, default to true)
     * @param  string|null $orderby LogDate desc (optional, default to 'LogDate desc')
     * @param  string|null $select NewValue (optional)
     * @param  int|null $skip skips the first x entries of the response(paging) (optional)
     * @param  int|null $top limits the number of returned records. (optional, default to 1000)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v10AuditLogEntriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function v10AuditLogEntriesGetRequest($expand = null, $filter = null, $search_string = null, $count = true, $orderby = 'LogDate desc', $select = null, $skip = null, $top = 1000, string $contentType = self::contentTypes['v10AuditLogEntriesGet'][0])
    {










        $resourcePath = '/v1.0/auditLogEntries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_string,
            'searchString', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $count,
            '$count', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderby,
            '$orderby', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            '$skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $top,
            '$top', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
