<?php
/**
 * AccessCheckOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * AccessCheckOutput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccessCheckOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccessCheckOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'access_decision' => 'string',
        'access_deny_reason' => 'string',
        'access_allowed_condition' => 'string',
        'checked_access_right_id' => 'string',
        'checked_person_id' => 'string',
        'checked_date_time' => '\DateTime',
        'access_decision_tree' => 'mixed[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'access_decision' => null,
        'access_deny_reason' => null,
        'access_allowed_condition' => null,
        'checked_access_right_id' => null,
        'checked_person_id' => null,
        'checked_date_time' => 'date-time',
        'access_decision_tree' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'access_decision' => false,
        'access_deny_reason' => false,
        'access_allowed_condition' => false,
        'checked_access_right_id' => false,
        'checked_person_id' => false,
        'checked_date_time' => false,
        'access_decision_tree' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_decision' => 'AccessDecision',
        'access_deny_reason' => 'AccessDenyReason',
        'access_allowed_condition' => 'AccessAllowedCondition',
        'checked_access_right_id' => 'CheckedAccessRightId',
        'checked_person_id' => 'CheckedPersonId',
        'checked_date_time' => 'CheckedDateTime',
        'access_decision_tree' => 'AccessDecisionTree'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_decision' => 'setAccessDecision',
        'access_deny_reason' => 'setAccessDenyReason',
        'access_allowed_condition' => 'setAccessAllowedCondition',
        'checked_access_right_id' => 'setCheckedAccessRightId',
        'checked_person_id' => 'setCheckedPersonId',
        'checked_date_time' => 'setCheckedDateTime',
        'access_decision_tree' => 'setAccessDecisionTree'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_decision' => 'getAccessDecision',
        'access_deny_reason' => 'getAccessDenyReason',
        'access_allowed_condition' => 'getAccessAllowedCondition',
        'checked_access_right_id' => 'getCheckedAccessRightId',
        'checked_person_id' => 'getCheckedPersonId',
        'checked_date_time' => 'getCheckedDateTime',
        'access_decision_tree' => 'getAccessDecisionTree'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ACCESS_DECISION_UNKNOWN = 'Unknown';
    public const ACCESS_DECISION_ACCESS_ALLOWED = 'AccessAllowed';
    public const ACCESS_DECISION_ACCESS_DENIED = 'AccessDenied';
    public const ACCESS_DENY_REASON_UNKNOWN = 'Unknown';
    public const ACCESS_DENY_REASON_PERSON_BLOCKED = 'PersonBlocked';
    public const ACCESS_DENY_REASON_PERSON_ACCESS_EXIT_DATE_IN_PAST = 'PersonAccessExitDateInPast';
    public const ACCESS_DENY_REASON_ACCESS_RIGHT_NOT_ACTIVE = 'AccessRightNotActive';
    public const ACCESS_DENY_REASON_INSUFICIENT_SECURITY_LEVEL = 'InsuficientSecurityLevel';
    public const ACCESS_DENY_REASON_ACCESS_RIGHT_VALID_FROM_IN_FUTURE = 'AccessRightValidFromInFuture';
    public const ACCESS_DENY_REASON_ASSIGNMENT_VALID_FROM_IN_FUTURE = 'AssignmentValidFromInFuture';
    public const ACCESS_DENY_REASON_ACCESS_RIGHT_VALID_TO_IN_PAST = 'AccessRightValidToInPast';
    public const ACCESS_DENY_REASON_ASSIGNMENT_VALID_TO_IN_PAST = 'AssignmentValidToInPast';
    public const ACCESS_DENY_REASON_TIME_ZONE_NOT_VALID = 'TimeZoneNotValid';
    public const ACCESS_DENY_REASON_NO_VALID_ACCESS_RIGHT_ASSIGNMENT_FOUND = 'NoValidAccessRightAssignmentFound';
    public const ACCESS_DENY_REASON_NOT_THE_REQUESTED_ACCESS_RIGHT = 'NotTheRequestedAccessRight';
    public const ACCESS_ALLOWED_CONDITION_NONE = 'None';
    public const ACCESS_ALLOWED_CONDITION_PIN_REQUIRED = 'PinRequired';
    public const ACCESS_ALLOWED_CONDITION_BIO_REQUIRED = 'BioRequired';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccessDecisionAllowableValues()
    {
        return [
            self::ACCESS_DECISION_UNKNOWN,
            self::ACCESS_DECISION_ACCESS_ALLOWED,
            self::ACCESS_DECISION_ACCESS_DENIED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccessDenyReasonAllowableValues()
    {
        return [
            self::ACCESS_DENY_REASON_UNKNOWN,
            self::ACCESS_DENY_REASON_PERSON_BLOCKED,
            self::ACCESS_DENY_REASON_PERSON_ACCESS_EXIT_DATE_IN_PAST,
            self::ACCESS_DENY_REASON_ACCESS_RIGHT_NOT_ACTIVE,
            self::ACCESS_DENY_REASON_INSUFICIENT_SECURITY_LEVEL,
            self::ACCESS_DENY_REASON_ACCESS_RIGHT_VALID_FROM_IN_FUTURE,
            self::ACCESS_DENY_REASON_ASSIGNMENT_VALID_FROM_IN_FUTURE,
            self::ACCESS_DENY_REASON_ACCESS_RIGHT_VALID_TO_IN_PAST,
            self::ACCESS_DENY_REASON_ASSIGNMENT_VALID_TO_IN_PAST,
            self::ACCESS_DENY_REASON_TIME_ZONE_NOT_VALID,
            self::ACCESS_DENY_REASON_NO_VALID_ACCESS_RIGHT_ASSIGNMENT_FOUND,
            self::ACCESS_DENY_REASON_NOT_THE_REQUESTED_ACCESS_RIGHT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccessAllowedConditionAllowableValues()
    {
        return [
            self::ACCESS_ALLOWED_CONDITION_NONE,
            self::ACCESS_ALLOWED_CONDITION_PIN_REQUIRED,
            self::ACCESS_ALLOWED_CONDITION_BIO_REQUIRED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('access_decision', $data ?? [], 'Unknown');
        $this->setIfExists('access_deny_reason', $data ?? [], 'Unknown');
        $this->setIfExists('access_allowed_condition', $data ?? [], 'None');
        $this->setIfExists('checked_access_right_id', $data ?? [], 'AccessRight1');
        $this->setIfExists('checked_person_id', $data ?? [], 'Person1');
        $this->setIfExists('checked_date_time', $data ?? [], null);
        $this->setIfExists('access_decision_tree', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['access_decision'] === null) {
            $invalidProperties[] = "'access_decision' can't be null";
        }
        $allowedValues = $this->getAccessDecisionAllowableValues();
        if (!is_null($this->container['access_decision']) && !in_array($this->container['access_decision'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'access_decision', must be one of '%s'",
                $this->container['access_decision'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['access_deny_reason'] === null) {
            $invalidProperties[] = "'access_deny_reason' can't be null";
        }
        $allowedValues = $this->getAccessDenyReasonAllowableValues();
        if (!is_null($this->container['access_deny_reason']) && !in_array($this->container['access_deny_reason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'access_deny_reason', must be one of '%s'",
                $this->container['access_deny_reason'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['access_allowed_condition'] === null) {
            $invalidProperties[] = "'access_allowed_condition' can't be null";
        }
        $allowedValues = $this->getAccessAllowedConditionAllowableValues();
        if (!is_null($this->container['access_allowed_condition']) && !in_array($this->container['access_allowed_condition'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'access_allowed_condition', must be one of '%s'",
                $this->container['access_allowed_condition'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['checked_access_right_id'] === null) {
            $invalidProperties[] = "'checked_access_right_id' can't be null";
        }
        if ($this->container['checked_person_id'] === null) {
            $invalidProperties[] = "'checked_person_id' can't be null";
        }
        if ($this->container['checked_date_time'] === null) {
            $invalidProperties[] = "'checked_date_time' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_decision
     *
     * @return string
     */
    public function getAccessDecision()
    {
        return $this->container['access_decision'];
    }

    /**
     * Sets access_decision
     *
     * @param string $access_decision access_decision
     *
     * @return self
     */
    public function setAccessDecision($access_decision)
    {
        if (is_null($access_decision)) {
            throw new \InvalidArgumentException('non-nullable access_decision cannot be null');
        }
        $allowedValues = $this->getAccessDecisionAllowableValues();
        if (!in_array($access_decision, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'access_decision', must be one of '%s'",
                    $access_decision,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['access_decision'] = $access_decision;

        return $this;
    }

    /**
     * Gets access_deny_reason
     *
     * @return string
     */
    public function getAccessDenyReason()
    {
        return $this->container['access_deny_reason'];
    }

    /**
     * Sets access_deny_reason
     *
     * @param string $access_deny_reason access_deny_reason
     *
     * @return self
     */
    public function setAccessDenyReason($access_deny_reason)
    {
        if (is_null($access_deny_reason)) {
            throw new \InvalidArgumentException('non-nullable access_deny_reason cannot be null');
        }
        $allowedValues = $this->getAccessDenyReasonAllowableValues();
        if (!in_array($access_deny_reason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'access_deny_reason', must be one of '%s'",
                    $access_deny_reason,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['access_deny_reason'] = $access_deny_reason;

        return $this;
    }

    /**
     * Gets access_allowed_condition
     *
     * @return string
     */
    public function getAccessAllowedCondition()
    {
        return $this->container['access_allowed_condition'];
    }

    /**
     * Sets access_allowed_condition
     *
     * @param string $access_allowed_condition access_allowed_condition
     *
     * @return self
     */
    public function setAccessAllowedCondition($access_allowed_condition)
    {
        if (is_null($access_allowed_condition)) {
            throw new \InvalidArgumentException('non-nullable access_allowed_condition cannot be null');
        }
        $allowedValues = $this->getAccessAllowedConditionAllowableValues();
        if (!in_array($access_allowed_condition, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'access_allowed_condition', must be one of '%s'",
                    $access_allowed_condition,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['access_allowed_condition'] = $access_allowed_condition;

        return $this;
    }

    /**
     * Gets checked_access_right_id
     *
     * @return string
     */
    public function getCheckedAccessRightId()
    {
        return $this->container['checked_access_right_id'];
    }

    /**
     * Sets checked_access_right_id
     *
     * @param string $checked_access_right_id checked_access_right_id
     *
     * @return self
     */
    public function setCheckedAccessRightId($checked_access_right_id)
    {
        if (is_null($checked_access_right_id)) {
            throw new \InvalidArgumentException('non-nullable checked_access_right_id cannot be null');
        }
        $this->container['checked_access_right_id'] = $checked_access_right_id;

        return $this;
    }

    /**
     * Gets checked_person_id
     *
     * @return string
     */
    public function getCheckedPersonId()
    {
        return $this->container['checked_person_id'];
    }

    /**
     * Sets checked_person_id
     *
     * @param string $checked_person_id checked_person_id
     *
     * @return self
     */
    public function setCheckedPersonId($checked_person_id)
    {
        if (is_null($checked_person_id)) {
            throw new \InvalidArgumentException('non-nullable checked_person_id cannot be null');
        }
        $this->container['checked_person_id'] = $checked_person_id;

        return $this;
    }

    /**
     * Gets checked_date_time
     *
     * @return \DateTime
     */
    public function getCheckedDateTime()
    {
        return $this->container['checked_date_time'];
    }

    /**
     * Sets checked_date_time
     *
     * @param \DateTime $checked_date_time checked_date_time
     *
     * @return self
     */
    public function setCheckedDateTime($checked_date_time)
    {
        if (is_null($checked_date_time)) {
            throw new \InvalidArgumentException('non-nullable checked_date_time cannot be null');
        }
        $this->container['checked_date_time'] = $checked_date_time;

        return $this;
    }

    /**
     * Gets access_decision_tree
     *
     * @return mixed[]|null
     */
    public function getAccessDecisionTree()
    {
        return $this->container['access_decision_tree'];
    }

    /**
     * Sets access_decision_tree
     *
     * @param mixed[]|null $access_decision_tree access_decision_tree
     *
     * @return self
     */
    public function setAccessDecisionTree($access_decision_tree)
    {
        if (is_null($access_decision_tree)) {
            array_push($this->openAPINullablesSetToNull, 'access_decision_tree');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('access_decision_tree', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['access_decision_tree'] = $access_decision_tree;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


