<?php
/**
 * GetAuthorisationOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * GetAuthorisationOutput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetAuthorisationOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetAuthorisationOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'identification' => 'string',
        'authorisation_group_id' => 'string',
        'authorisation_group_name' => 'string',
        'authorisation_group_description' => 'string',
        'authorisation_id_internal' => 'int',
        'auth_id' => 'string',
        'authorisation_name' => 'string',
        'authorisation_description' => 'string',
        'authorisation_value' => '\Exos\ExosApi\Model\AuthorisationValueType',
        'is_authorisation_tri_state' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'identification' => null,
        'authorisation_group_id' => null,
        'authorisation_group_name' => null,
        'authorisation_group_description' => null,
        'authorisation_id_internal' => 'int32',
        'auth_id' => null,
        'authorisation_name' => null,
        'authorisation_description' => null,
        'authorisation_value' => null,
        'is_authorisation_tri_state' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'identification' => true,
        'authorisation_group_id' => true,
        'authorisation_group_name' => true,
        'authorisation_group_description' => true,
        'authorisation_id_internal' => true,
        'auth_id' => true,
        'authorisation_name' => true,
        'authorisation_description' => true,
        'authorisation_value' => true,
        'is_authorisation_tri_state' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'identification' => 'Identification',
        'authorisation_group_id' => 'AuthorisationGroupId',
        'authorisation_group_name' => 'AuthorisationGroupName',
        'authorisation_group_description' => 'AuthorisationGroupDescription',
        'authorisation_id_internal' => 'AuthorisationIdInternal',
        'auth_id' => 'AuthId',
        'authorisation_name' => 'AuthorisationName',
        'authorisation_description' => 'AuthorisationDescription',
        'authorisation_value' => 'AuthorisationValue',
        'is_authorisation_tri_state' => 'IsAuthorisationTriState'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'identification' => 'setIdentification',
        'authorisation_group_id' => 'setAuthorisationGroupId',
        'authorisation_group_name' => 'setAuthorisationGroupName',
        'authorisation_group_description' => 'setAuthorisationGroupDescription',
        'authorisation_id_internal' => 'setAuthorisationIdInternal',
        'auth_id' => 'setAuthId',
        'authorisation_name' => 'setAuthorisationName',
        'authorisation_description' => 'setAuthorisationDescription',
        'authorisation_value' => 'setAuthorisationValue',
        'is_authorisation_tri_state' => 'setIsAuthorisationTriState'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'identification' => 'getIdentification',
        'authorisation_group_id' => 'getAuthorisationGroupId',
        'authorisation_group_name' => 'getAuthorisationGroupName',
        'authorisation_group_description' => 'getAuthorisationGroupDescription',
        'authorisation_id_internal' => 'getAuthorisationIdInternal',
        'auth_id' => 'getAuthId',
        'authorisation_name' => 'getAuthorisationName',
        'authorisation_description' => 'getAuthorisationDescription',
        'authorisation_value' => 'getAuthorisationValue',
        'is_authorisation_tri_state' => 'getIsAuthorisationTriState'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('identification', $data ?? [], 'GUID');
        $this->setIfExists('authorisation_group_id', $data ?? [], 'GroupId');
        $this->setIfExists('authorisation_group_name', $data ?? [], 'GroupName');
        $this->setIfExists('authorisation_group_description', $data ?? [], 'GroupDescription');
        $this->setIfExists('authorisation_id_internal', $data ?? [], 1);
        $this->setIfExists('auth_id', $data ?? [], 'API_SDM_EmployeeRead');
        $this->setIfExists('authorisation_name', $data ?? [], 'Show employee data');
        $this->setIfExists('authorisation_description', $data ?? [], 'Right for: Show employee data');
        $this->setIfExists('authorisation_value', $data ?? [], null);
        $this->setIfExists('is_authorisation_tri_state', $data ?? [], false);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets identification
     *
     * @return string|null
     */
    public function getIdentification()
    {
        return $this->container['identification'];
    }

    /**
     * Sets identification
     *
     * @param string|null $identification identification
     *
     * @return self
     */
    public function setIdentification($identification)
    {
        if (is_null($identification)) {
            array_push($this->openAPINullablesSetToNull, 'identification');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identification', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identification'] = $identification;

        return $this;
    }

    /**
     * Gets authorisation_group_id
     *
     * @return string|null
     */
    public function getAuthorisationGroupId()
    {
        return $this->container['authorisation_group_id'];
    }

    /**
     * Sets authorisation_group_id
     *
     * @param string|null $authorisation_group_id authorisation_group_id
     *
     * @return self
     */
    public function setAuthorisationGroupId($authorisation_group_id)
    {
        if (is_null($authorisation_group_id)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_group_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_group_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_group_id'] = $authorisation_group_id;

        return $this;
    }

    /**
     * Gets authorisation_group_name
     *
     * @return string|null
     */
    public function getAuthorisationGroupName()
    {
        return $this->container['authorisation_group_name'];
    }

    /**
     * Sets authorisation_group_name
     *
     * @param string|null $authorisation_group_name authorisation_group_name
     *
     * @return self
     */
    public function setAuthorisationGroupName($authorisation_group_name)
    {
        if (is_null($authorisation_group_name)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_group_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_group_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_group_name'] = $authorisation_group_name;

        return $this;
    }

    /**
     * Gets authorisation_group_description
     *
     * @return string|null
     */
    public function getAuthorisationGroupDescription()
    {
        return $this->container['authorisation_group_description'];
    }

    /**
     * Sets authorisation_group_description
     *
     * @param string|null $authorisation_group_description authorisation_group_description
     *
     * @return self
     */
    public function setAuthorisationGroupDescription($authorisation_group_description)
    {
        if (is_null($authorisation_group_description)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_group_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_group_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_group_description'] = $authorisation_group_description;

        return $this;
    }

    /**
     * Gets authorisation_id_internal
     *
     * @return int|null
     */
    public function getAuthorisationIdInternal()
    {
        return $this->container['authorisation_id_internal'];
    }

    /**
     * Sets authorisation_id_internal
     *
     * @param int|null $authorisation_id_internal authorisation_id_internal
     *
     * @return self
     */
    public function setAuthorisationIdInternal($authorisation_id_internal)
    {
        if (is_null($authorisation_id_internal)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_id_internal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_id_internal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_id_internal'] = $authorisation_id_internal;

        return $this;
    }

    /**
     * Gets auth_id
     *
     * @return string|null
     */
    public function getAuthId()
    {
        return $this->container['auth_id'];
    }

    /**
     * Sets auth_id
     *
     * @param string|null $auth_id auth_id
     *
     * @return self
     */
    public function setAuthId($auth_id)
    {
        if (is_null($auth_id)) {
            array_push($this->openAPINullablesSetToNull, 'auth_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auth_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auth_id'] = $auth_id;

        return $this;
    }

    /**
     * Gets authorisation_name
     *
     * @return string|null
     */
    public function getAuthorisationName()
    {
        return $this->container['authorisation_name'];
    }

    /**
     * Sets authorisation_name
     *
     * @param string|null $authorisation_name authorisation_name
     *
     * @return self
     */
    public function setAuthorisationName($authorisation_name)
    {
        if (is_null($authorisation_name)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_name'] = $authorisation_name;

        return $this;
    }

    /**
     * Gets authorisation_description
     *
     * @return string|null
     */
    public function getAuthorisationDescription()
    {
        return $this->container['authorisation_description'];
    }

    /**
     * Sets authorisation_description
     *
     * @param string|null $authorisation_description authorisation_description
     *
     * @return self
     */
    public function setAuthorisationDescription($authorisation_description)
    {
        if (is_null($authorisation_description)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_description'] = $authorisation_description;

        return $this;
    }

    /**
     * Gets authorisation_value
     *
     * @return \Exos\ExosApi\Model\AuthorisationValueType|null
     */
    public function getAuthorisationValue()
    {
        return $this->container['authorisation_value'];
    }

    /**
     * Sets authorisation_value
     *
     * @param \Exos\ExosApi\Model\AuthorisationValueType|null $authorisation_value authorisation_value
     *
     * @return self
     */
    public function setAuthorisationValue($authorisation_value)
    {
        if (is_null($authorisation_value)) {
            array_push($this->openAPINullablesSetToNull, 'authorisation_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authorisation_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authorisation_value'] = $authorisation_value;

        return $this;
    }

    /**
     * Gets is_authorisation_tri_state
     *
     * @return bool|null
     */
    public function getIsAuthorisationTriState()
    {
        return $this->container['is_authorisation_tri_state'];
    }

    /**
     * Sets is_authorisation_tri_state
     *
     * @param bool|null $is_authorisation_tri_state is_authorisation_tri_state
     *
     * @return self
     */
    public function setIsAuthorisationTriState($is_authorisation_tri_state)
    {
        if (is_null($is_authorisation_tri_state)) {
            array_push($this->openAPINullablesSetToNull, 'is_authorisation_tri_state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_authorisation_tri_state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_authorisation_tri_state'] = $is_authorisation_tri_state;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


