<?php
/**
 * GetDownloadLogEntryOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * GetDownloadLogEntryOutput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetDownloadLogEntryOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetDownloadLogEntryOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'log_id_internal' => 'int',
        'log_date' => '\DateTime',
        'frontserver_fk' => 'int',
        'front_server' => '\Exos\ExosApi\Model\FrontServer',
        'login' => 'string',
        'command' => 'string',
        'main_key' => 'string',
        'sub_key' => 'string',
        'priority' => 'int',
        'date_expired' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'log_id_internal' => 'int64',
        'log_date' => 'date-time',
        'frontserver_fk' => 'int64',
        'front_server' => null,
        'login' => null,
        'command' => null,
        'main_key' => null,
        'sub_key' => null,
        'priority' => 'int64',
        'date_expired' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'log_id_internal' => false,
        'log_date' => true,
        'frontserver_fk' => true,
        'front_server' => false,
        'login' => false,
        'command' => false,
        'main_key' => true,
        'sub_key' => true,
        'priority' => true,
        'date_expired' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'log_id_internal' => 'LogIdInternal',
        'log_date' => 'LogDate',
        'frontserver_fk' => 'FrontserverFK',
        'front_server' => 'FrontServer',
        'login' => 'Login',
        'command' => 'Command',
        'main_key' => 'MainKey',
        'sub_key' => 'SubKey',
        'priority' => 'Priority',
        'date_expired' => 'DateExpired'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'log_id_internal' => 'setLogIdInternal',
        'log_date' => 'setLogDate',
        'frontserver_fk' => 'setFrontserverFk',
        'front_server' => 'setFrontServer',
        'login' => 'setLogin',
        'command' => 'setCommand',
        'main_key' => 'setMainKey',
        'sub_key' => 'setSubKey',
        'priority' => 'setPriority',
        'date_expired' => 'setDateExpired'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'log_id_internal' => 'getLogIdInternal',
        'log_date' => 'getLogDate',
        'frontserver_fk' => 'getFrontserverFk',
        'front_server' => 'getFrontServer',
        'login' => 'getLogin',
        'command' => 'getCommand',
        'main_key' => 'getMainKey',
        'sub_key' => 'getSubKey',
        'priority' => 'getPriority',
        'date_expired' => 'getDateExpired'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('log_id_internal', $data ?? [], 1);
        $this->setIfExists('log_date', $data ?? [], null);
        $this->setIfExists('frontserver_fk', $data ?? [], 1);
        $this->setIfExists('front_server', $data ?? [], null);
        $this->setIfExists('login', $data ?? [], '');
        $this->setIfExists('command', $data ?? [], '');
        $this->setIfExists('main_key', $data ?? [], '');
        $this->setIfExists('sub_key', $data ?? [], '');
        $this->setIfExists('priority', $data ?? [], 1);
        $this->setIfExists('date_expired', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets log_id_internal
     *
     * @return int|null
     */
    public function getLogIdInternal()
    {
        return $this->container['log_id_internal'];
    }

    /**
     * Sets log_id_internal
     *
     * @param int|null $log_id_internal log_id_internal
     *
     * @return self
     */
    public function setLogIdInternal($log_id_internal)
    {
        if (is_null($log_id_internal)) {
            throw new \InvalidArgumentException('non-nullable log_id_internal cannot be null');
        }
        $this->container['log_id_internal'] = $log_id_internal;

        return $this;
    }

    /**
     * Gets log_date
     *
     * @return \DateTime|null
     */
    public function getLogDate()
    {
        return $this->container['log_date'];
    }

    /**
     * Sets log_date
     *
     * @param \DateTime|null $log_date log_date
     *
     * @return self
     */
    public function setLogDate($log_date)
    {
        if (is_null($log_date)) {
            array_push($this->openAPINullablesSetToNull, 'log_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('log_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['log_date'] = $log_date;

        return $this;
    }

    /**
     * Gets frontserver_fk
     *
     * @return int|null
     */
    public function getFrontserverFk()
    {
        return $this->container['frontserver_fk'];
    }

    /**
     * Sets frontserver_fk
     *
     * @param int|null $frontserver_fk frontserver_fk
     *
     * @return self
     */
    public function setFrontserverFk($frontserver_fk)
    {
        if (is_null($frontserver_fk)) {
            array_push($this->openAPINullablesSetToNull, 'frontserver_fk');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('frontserver_fk', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['frontserver_fk'] = $frontserver_fk;

        return $this;
    }

    /**
     * Gets front_server
     *
     * @return \Exos\ExosApi\Model\FrontServer|null
     */
    public function getFrontServer()
    {
        return $this->container['front_server'];
    }

    /**
     * Sets front_server
     *
     * @param \Exos\ExosApi\Model\FrontServer|null $front_server front_server
     *
     * @return self
     */
    public function setFrontServer($front_server)
    {
        if (is_null($front_server)) {
            throw new \InvalidArgumentException('non-nullable front_server cannot be null');
        }
        $this->container['front_server'] = $front_server;

        return $this;
    }

    /**
     * Gets login
     *
     * @return string|null
     */
    public function getLogin()
    {
        return $this->container['login'];
    }

    /**
     * Sets login
     *
     * @param string|null $login login
     *
     * @return self
     */
    public function setLogin($login)
    {
        if (is_null($login)) {
            throw new \InvalidArgumentException('non-nullable login cannot be null');
        }
        $this->container['login'] = $login;

        return $this;
    }

    /**
     * Gets command
     *
     * @return string|null
     */
    public function getCommand()
    {
        return $this->container['command'];
    }

    /**
     * Sets command
     *
     * @param string|null $command command
     *
     * @return self
     */
    public function setCommand($command)
    {
        if (is_null($command)) {
            throw new \InvalidArgumentException('non-nullable command cannot be null');
        }
        $this->container['command'] = $command;

        return $this;
    }

    /**
     * Gets main_key
     *
     * @return string|null
     */
    public function getMainKey()
    {
        return $this->container['main_key'];
    }

    /**
     * Sets main_key
     *
     * @param string|null $main_key main_key
     *
     * @return self
     */
    public function setMainKey($main_key)
    {
        if (is_null($main_key)) {
            array_push($this->openAPINullablesSetToNull, 'main_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('main_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['main_key'] = $main_key;

        return $this;
    }

    /**
     * Gets sub_key
     *
     * @return string|null
     */
    public function getSubKey()
    {
        return $this->container['sub_key'];
    }

    /**
     * Sets sub_key
     *
     * @param string|null $sub_key sub_key
     *
     * @return self
     */
    public function setSubKey($sub_key)
    {
        if (is_null($sub_key)) {
            array_push($this->openAPINullablesSetToNull, 'sub_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sub_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sub_key'] = $sub_key;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int|null
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int|null $priority priority
     *
     * @return self
     */
    public function setPriority($priority)
    {
        if (is_null($priority)) {
            array_push($this->openAPINullablesSetToNull, 'priority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('priority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets date_expired
     *
     * @return \DateTime|null
     */
    public function getDateExpired()
    {
        return $this->container['date_expired'];
    }

    /**
     * Sets date_expired
     *
     * @param \DateTime|null $date_expired date_expired
     *
     * @return self
     */
    public function setDateExpired($date_expired)
    {
        if (is_null($date_expired)) {
            array_push($this->openAPINullablesSetToNull, 'date_expired');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_expired', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_expired'] = $date_expired;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


