<?php
/**
 * GetPersonOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * GetPersonOutput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetPersonOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetPersonOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'person_id_internal' => 'int',
        'tenant_id' => 'int',
        'person_base_data' => '\Exos\ExosApi\Model\PersonBaseDataOutput',
        'person_access_control_data' => '\Exos\ExosApi\Model\PersonAccessControlDataOutput',
        'person_tenant_free_fields' => '\Exos\ExosApi\Model\PersonTenantFreeFieldsOutput',
        'person_image_data' => '\Exos\ExosApi\Model\PersonImageDataOutput',
        'person_security_data' => '\Exos\ExosApi\Model\PersonSecurityDataOutput',
        'person_sap_data' => '\Exos\ExosApi\Model\PersonSAPDataOutput',
        'category' => '\Exos\ExosApi\Model\PersonCategoryOutput',
        'tenant' => '\Exos\ExosApi\Model\TenantOutput',
        'badge' => '\Exos\ExosApi\Model\GetBadgeOutput[]',
        'keys' => '\Exos\ExosApi\Model\GetKeyOutput[]',
        'key_rings' => '\Exos\ExosApi\Model\GetKeyRingOutput[]',
        'person_office_flow_data' => '\Exos\ExosApi\Model\PersonOfficeFlowDataOutput',
        'person_time_and_attendance_data' => '\Exos\ExosApi\Model\PersonTimeAndAttendanceDataOutput'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'person_id_internal' => 'int32',
        'tenant_id' => 'int32',
        'person_base_data' => null,
        'person_access_control_data' => null,
        'person_tenant_free_fields' => null,
        'person_image_data' => null,
        'person_security_data' => null,
        'person_sap_data' => null,
        'category' => null,
        'tenant' => null,
        'badge' => null,
        'keys' => null,
        'key_rings' => null,
        'person_office_flow_data' => null,
        'person_time_and_attendance_data' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'person_id_internal' => false,
        'tenant_id' => false,
        'person_base_data' => true,
        'person_access_control_data' => true,
        'person_tenant_free_fields' => true,
        'person_image_data' => true,
        'person_security_data' => true,
        'person_sap_data' => true,
        'category' => true,
        'tenant' => true,
        'badge' => true,
        'keys' => true,
        'key_rings' => true,
        'person_office_flow_data' => false,
        'person_time_and_attendance_data' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'person_id_internal' => 'PersonIdInternal',
        'tenant_id' => 'TenantId',
        'person_base_data' => 'PersonBaseData',
        'person_access_control_data' => 'PersonAccessControlData',
        'person_tenant_free_fields' => 'PersonTenantFreeFields',
        'person_image_data' => 'PersonImageData',
        'person_security_data' => 'PersonSecurityData',
        'person_sap_data' => 'PersonSAPData',
        'category' => 'Category',
        'tenant' => 'Tenant',
        'badge' => 'Badge',
        'keys' => 'Keys',
        'key_rings' => 'KeyRings',
        'person_office_flow_data' => 'PersonOfficeFlowData',
        'person_time_and_attendance_data' => 'PersonTimeAndAttendanceData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'person_id_internal' => 'setPersonIdInternal',
        'tenant_id' => 'setTenantId',
        'person_base_data' => 'setPersonBaseData',
        'person_access_control_data' => 'setPersonAccessControlData',
        'person_tenant_free_fields' => 'setPersonTenantFreeFields',
        'person_image_data' => 'setPersonImageData',
        'person_security_data' => 'setPersonSecurityData',
        'person_sap_data' => 'setPersonSapData',
        'category' => 'setCategory',
        'tenant' => 'setTenant',
        'badge' => 'setBadge',
        'keys' => 'setKeys',
        'key_rings' => 'setKeyRings',
        'person_office_flow_data' => 'setPersonOfficeFlowData',
        'person_time_and_attendance_data' => 'setPersonTimeAndAttendanceData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'person_id_internal' => 'getPersonIdInternal',
        'tenant_id' => 'getTenantId',
        'person_base_data' => 'getPersonBaseData',
        'person_access_control_data' => 'getPersonAccessControlData',
        'person_tenant_free_fields' => 'getPersonTenantFreeFields',
        'person_image_data' => 'getPersonImageData',
        'person_security_data' => 'getPersonSecurityData',
        'person_sap_data' => 'getPersonSapData',
        'category' => 'getCategory',
        'tenant' => 'getTenant',
        'badge' => 'getBadge',
        'keys' => 'getKeys',
        'key_rings' => 'getKeyRings',
        'person_office_flow_data' => 'getPersonOfficeFlowData',
        'person_time_and_attendance_data' => 'getPersonTimeAndAttendanceData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('person_id_internal', $data ?? [], 1);
        $this->setIfExists('tenant_id', $data ?? [], 1);
        $this->setIfExists('person_base_data', $data ?? [], null);
        $this->setIfExists('person_access_control_data', $data ?? [], null);
        $this->setIfExists('person_tenant_free_fields', $data ?? [], null);
        $this->setIfExists('person_image_data', $data ?? [], null);
        $this->setIfExists('person_security_data', $data ?? [], null);
        $this->setIfExists('person_sap_data', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('tenant', $data ?? [], null);
        $this->setIfExists('badge', $data ?? [], null);
        $this->setIfExists('keys', $data ?? [], null);
        $this->setIfExists('key_rings', $data ?? [], null);
        $this->setIfExists('person_office_flow_data', $data ?? [], null);
        $this->setIfExists('person_time_and_attendance_data', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['person_id_internal'] === null) {
            $invalidProperties[] = "'person_id_internal' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets person_id_internal
     *
     * @return int
     */
    public function getPersonIdInternal()
    {
        return $this->container['person_id_internal'];
    }

    /**
     * Sets person_id_internal
     *
     * @param int $person_id_internal person_id_internal
     *
     * @return self
     */
    public function setPersonIdInternal($person_id_internal)
    {
        if (is_null($person_id_internal)) {
            throw new \InvalidArgumentException('non-nullable person_id_internal cannot be null');
        }
        $this->container['person_id_internal'] = $person_id_internal;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets person_base_data
     *
     * @return \Exos\ExosApi\Model\PersonBaseDataOutput|null
     */
    public function getPersonBaseData()
    {
        return $this->container['person_base_data'];
    }

    /**
     * Sets person_base_data
     *
     * @param \Exos\ExosApi\Model\PersonBaseDataOutput|null $person_base_data person_base_data
     *
     * @return self
     */
    public function setPersonBaseData($person_base_data)
    {
        if (is_null($person_base_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_base_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_base_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_base_data'] = $person_base_data;

        return $this;
    }

    /**
     * Gets person_access_control_data
     *
     * @return \Exos\ExosApi\Model\PersonAccessControlDataOutput|null
     */
    public function getPersonAccessControlData()
    {
        return $this->container['person_access_control_data'];
    }

    /**
     * Sets person_access_control_data
     *
     * @param \Exos\ExosApi\Model\PersonAccessControlDataOutput|null $person_access_control_data person_access_control_data
     *
     * @return self
     */
    public function setPersonAccessControlData($person_access_control_data)
    {
        if (is_null($person_access_control_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_access_control_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_access_control_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_access_control_data'] = $person_access_control_data;

        return $this;
    }

    /**
     * Gets person_tenant_free_fields
     *
     * @return \Exos\ExosApi\Model\PersonTenantFreeFieldsOutput|null
     */
    public function getPersonTenantFreeFields()
    {
        return $this->container['person_tenant_free_fields'];
    }

    /**
     * Sets person_tenant_free_fields
     *
     * @param \Exos\ExosApi\Model\PersonTenantFreeFieldsOutput|null $person_tenant_free_fields person_tenant_free_fields
     *
     * @return self
     */
    public function setPersonTenantFreeFields($person_tenant_free_fields)
    {
        if (is_null($person_tenant_free_fields)) {
            array_push($this->openAPINullablesSetToNull, 'person_tenant_free_fields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_tenant_free_fields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_tenant_free_fields'] = $person_tenant_free_fields;

        return $this;
    }

    /**
     * Gets person_image_data
     *
     * @return \Exos\ExosApi\Model\PersonImageDataOutput|null
     */
    public function getPersonImageData()
    {
        return $this->container['person_image_data'];
    }

    /**
     * Sets person_image_data
     *
     * @param \Exos\ExosApi\Model\PersonImageDataOutput|null $person_image_data person_image_data
     *
     * @return self
     */
    public function setPersonImageData($person_image_data)
    {
        if (is_null($person_image_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_image_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_image_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_image_data'] = $person_image_data;

        return $this;
    }

    /**
     * Gets person_security_data
     *
     * @return \Exos\ExosApi\Model\PersonSecurityDataOutput|null
     */
    public function getPersonSecurityData()
    {
        return $this->container['person_security_data'];
    }

    /**
     * Sets person_security_data
     *
     * @param \Exos\ExosApi\Model\PersonSecurityDataOutput|null $person_security_data person_security_data
     *
     * @return self
     */
    public function setPersonSecurityData($person_security_data)
    {
        if (is_null($person_security_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_security_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_security_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_security_data'] = $person_security_data;

        return $this;
    }

    /**
     * Gets person_sap_data
     *
     * @return \Exos\ExosApi\Model\PersonSAPDataOutput|null
     */
    public function getPersonSapData()
    {
        return $this->container['person_sap_data'];
    }

    /**
     * Sets person_sap_data
     *
     * @param \Exos\ExosApi\Model\PersonSAPDataOutput|null $person_sap_data person_sap_data
     *
     * @return self
     */
    public function setPersonSapData($person_sap_data)
    {
        if (is_null($person_sap_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_sap_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_sap_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_sap_data'] = $person_sap_data;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \Exos\ExosApi\Model\PersonCategoryOutput|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \Exos\ExosApi\Model\PersonCategoryOutput|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            array_push($this->openAPINullablesSetToNull, 'category');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('category', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets tenant
     *
     * @return \Exos\ExosApi\Model\TenantOutput|null
     */
    public function getTenant()
    {
        return $this->container['tenant'];
    }

    /**
     * Sets tenant
     *
     * @param \Exos\ExosApi\Model\TenantOutput|null $tenant tenant
     *
     * @return self
     */
    public function setTenant($tenant)
    {
        if (is_null($tenant)) {
            array_push($this->openAPINullablesSetToNull, 'tenant');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenant', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenant'] = $tenant;

        return $this;
    }

    /**
     * Gets badge
     *
     * @return \Exos\ExosApi\Model\GetBadgeOutput[]|null
     */
    public function getBadge()
    {
        return $this->container['badge'];
    }

    /**
     * Sets badge
     *
     * @param \Exos\ExosApi\Model\GetBadgeOutput[]|null $badge badge
     *
     * @return self
     */
    public function setBadge($badge)
    {
        if (is_null($badge)) {
            array_push($this->openAPINullablesSetToNull, 'badge');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('badge', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['badge'] = $badge;

        return $this;
    }

    /**
     * Gets keys
     *
     * @return \Exos\ExosApi\Model\GetKeyOutput[]|null
     */
    public function getKeys()
    {
        return $this->container['keys'];
    }

    /**
     * Sets keys
     *
     * @param \Exos\ExosApi\Model\GetKeyOutput[]|null $keys keys
     *
     * @return self
     */
    public function setKeys($keys)
    {
        if (is_null($keys)) {
            array_push($this->openAPINullablesSetToNull, 'keys');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('keys', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['keys'] = $keys;

        return $this;
    }

    /**
     * Gets key_rings
     *
     * @return \Exos\ExosApi\Model\GetKeyRingOutput[]|null
     */
    public function getKeyRings()
    {
        return $this->container['key_rings'];
    }

    /**
     * Sets key_rings
     *
     * @param \Exos\ExosApi\Model\GetKeyRingOutput[]|null $key_rings key_rings
     *
     * @return self
     */
    public function setKeyRings($key_rings)
    {
        if (is_null($key_rings)) {
            array_push($this->openAPINullablesSetToNull, 'key_rings');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('key_rings', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['key_rings'] = $key_rings;

        return $this;
    }

    /**
     * Gets person_office_flow_data
     *
     * @return \Exos\ExosApi\Model\PersonOfficeFlowDataOutput|null
     */
    public function getPersonOfficeFlowData()
    {
        return $this->container['person_office_flow_data'];
    }

    /**
     * Sets person_office_flow_data
     *
     * @param \Exos\ExosApi\Model\PersonOfficeFlowDataOutput|null $person_office_flow_data person_office_flow_data
     *
     * @return self
     */
    public function setPersonOfficeFlowData($person_office_flow_data)
    {
        if (is_null($person_office_flow_data)) {
            throw new \InvalidArgumentException('non-nullable person_office_flow_data cannot be null');
        }
        $this->container['person_office_flow_data'] = $person_office_flow_data;

        return $this;
    }

    /**
     * Gets person_time_and_attendance_data
     *
     * @return \Exos\ExosApi\Model\PersonTimeAndAttendanceDataOutput|null
     */
    public function getPersonTimeAndAttendanceData()
    {
        return $this->container['person_time_and_attendance_data'];
    }

    /**
     * Sets person_time_and_attendance_data
     *
     * @param \Exos\ExosApi\Model\PersonTimeAndAttendanceDataOutput|null $person_time_and_attendance_data person_time_and_attendance_data
     *
     * @return self
     */
    public function setPersonTimeAndAttendanceData($person_time_and_attendance_data)
    {
        if (is_null($person_time_and_attendance_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_time_and_attendance_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_time_and_attendance_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_time_and_attendance_data'] = $person_time_and_attendance_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


