<?php
/**
 * GetTemporaryMasterMediaDefinitionsAndDataInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * GetTemporaryMasterMediaDefinitionsAndDataInput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetTemporaryMasterMediaDefinitionsAndDataInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetTemporaryMasterMediaDefinitionsAndDataInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'media_technology' => '\Exos\ExosApi\Model\MediaTechnology',
        'device_uid' => 'string',
        'access_domain_nr' => 'int',
        'validation_time_nr' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'media_technology' => null,
        'device_uid' => null,
        'access_domain_nr' => 'int32',
        'validation_time_nr' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'media_technology' => false,
        'device_uid' => false,
        'access_domain_nr' => false,
        'validation_time_nr' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'media_technology' => 'MediaTechnology',
        'device_uid' => 'DeviceUid',
        'access_domain_nr' => 'AccessDomainNr',
        'validation_time_nr' => 'ValidationTimeNr'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'media_technology' => 'setMediaTechnology',
        'device_uid' => 'setDeviceUid',
        'access_domain_nr' => 'setAccessDomainNr',
        'validation_time_nr' => 'setValidationTimeNr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'media_technology' => 'getMediaTechnology',
        'device_uid' => 'getDeviceUid',
        'access_domain_nr' => 'getAccessDomainNr',
        'validation_time_nr' => 'getValidationTimeNr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('media_technology', $data ?? [], null);
        $this->setIfExists('device_uid', $data ?? [], null);
        $this->setIfExists('access_domain_nr', $data ?? [], null);
        $this->setIfExists('validation_time_nr', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['media_technology'] === null) {
            $invalidProperties[] = "'media_technology' can't be null";
        }
        if ($this->container['device_uid'] === null) {
            $invalidProperties[] = "'device_uid' can't be null";
        }
        if ((mb_strlen($this->container['device_uid']) < 1)) {
            $invalidProperties[] = "invalid value for 'device_uid', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['access_domain_nr'] === null) {
            $invalidProperties[] = "'access_domain_nr' can't be null";
        }
        if ($this->container['validation_time_nr'] === null) {
            $invalidProperties[] = "'validation_time_nr' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets media_technology
     *
     * @return \Exos\ExosApi\Model\MediaTechnology
     */
    public function getMediaTechnology()
    {
        return $this->container['media_technology'];
    }

    /**
     * Sets media_technology
     *
     * @param \Exos\ExosApi\Model\MediaTechnology $media_technology media_technology
     *
     * @return self
     */
    public function setMediaTechnology($media_technology)
    {
        if (is_null($media_technology)) {
            throw new \InvalidArgumentException('non-nullable media_technology cannot be null');
        }
        $this->container['media_technology'] = $media_technology;

        return $this;
    }

    /**
     * Gets device_uid
     *
     * @return string
     */
    public function getDeviceUid()
    {
        return $this->container['device_uid'];
    }

    /**
     * Sets device_uid
     *
     * @param string $device_uid device_uid
     *
     * @return self
     */
    public function setDeviceUid($device_uid)
    {
        if (is_null($device_uid)) {
            throw new \InvalidArgumentException('non-nullable device_uid cannot be null');
        }

        if ((mb_strlen($device_uid) < 1)) {
            throw new \InvalidArgumentException('invalid length for $device_uid when calling GetTemporaryMasterMediaDefinitionsAndDataInput., must be bigger than or equal to 1.');
        }

        $this->container['device_uid'] = $device_uid;

        return $this;
    }

    /**
     * Gets access_domain_nr
     *
     * @return int
     */
    public function getAccessDomainNr()
    {
        return $this->container['access_domain_nr'];
    }

    /**
     * Sets access_domain_nr
     *
     * @param int $access_domain_nr access_domain_nr
     *
     * @return self
     */
    public function setAccessDomainNr($access_domain_nr)
    {
        if (is_null($access_domain_nr)) {
            throw new \InvalidArgumentException('non-nullable access_domain_nr cannot be null');
        }
        $this->container['access_domain_nr'] = $access_domain_nr;

        return $this;
    }

    /**
     * Gets validation_time_nr
     *
     * @return int
     */
    public function getValidationTimeNr()
    {
        return $this->container['validation_time_nr'];
    }

    /**
     * Sets validation_time_nr
     *
     * @param int $validation_time_nr validation_time_nr
     *
     * @return self
     */
    public function setValidationTimeNr($validation_time_nr)
    {
        if (is_null($validation_time_nr)) {
            throw new \InvalidArgumentException('non-nullable validation_time_nr cannot be null');
        }
        $this->container['validation_time_nr'] = $validation_time_nr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


