<?php
/**
 * PersonAccessControlDataOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * PersonAccessControlDataOutput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PersonAccessControlDataOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PersonAccessControlDataOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'person_id_internal' => 'int',
        'is_download_enabled' => 'bool',
        'current_number_of_invalid_pin_code_entries' => 'int',
        'access_exit_date' => '\DateTime',
        'last_access_date' => '\DateTime',
        'last_access_grid_id' => 'string',
        'last_access_domain_id' => 'string',
        'last_reader_address' => 'string',
        'last_reader_name' => 'string',
        'is_in_out_control_ignored' => 'bool',
        'is_antipassback_ignored' => 'bool',
        'is_min_max_person_in_room_ignored' => 'bool',
        'security_level' => 'int',
        'is_blocked' => 'bool',
        'is_media_traceback_enabled' => 'bool',
        'is_intervention_media_permitted' => 'bool',
        'is_fingerprint_unfeasible' => 'bool',
        'is_biometric_enabled' => 'bool',
        'extended_latch_time_active' => 'bool',
        'person_elevator_data' => '\Exos\ExosApi\Model\PersonElevatorDataOutput',
        'person_room_data' => '\Exos\ExosApi\Model\PersonRoomData',
        'access_rights' => '\Exos\ExosApi\Model\PersonAccessRights[]',
        'profiles' => '\Exos\ExosApi\Model\PersonProfiles[]',
        'has_individual_access_rights' => '\Exos\ExosApi\Model\PersonHasIndividualAccessRights[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'person_id_internal' => 'int32',
        'is_download_enabled' => null,
        'current_number_of_invalid_pin_code_entries' => 'int32',
        'access_exit_date' => 'date-time',
        'last_access_date' => 'date-time',
        'last_access_grid_id' => null,
        'last_access_domain_id' => null,
        'last_reader_address' => null,
        'last_reader_name' => null,
        'is_in_out_control_ignored' => null,
        'is_antipassback_ignored' => null,
        'is_min_max_person_in_room_ignored' => null,
        'security_level' => 'int32',
        'is_blocked' => null,
        'is_media_traceback_enabled' => null,
        'is_intervention_media_permitted' => null,
        'is_fingerprint_unfeasible' => null,
        'is_biometric_enabled' => null,
        'extended_latch_time_active' => null,
        'person_elevator_data' => null,
        'person_room_data' => null,
        'access_rights' => null,
        'profiles' => null,
        'has_individual_access_rights' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'person_id_internal' => true,
        'is_download_enabled' => true,
        'current_number_of_invalid_pin_code_entries' => true,
        'access_exit_date' => true,
        'last_access_date' => true,
        'last_access_grid_id' => true,
        'last_access_domain_id' => true,
        'last_reader_address' => true,
        'last_reader_name' => true,
        'is_in_out_control_ignored' => true,
        'is_antipassback_ignored' => true,
        'is_min_max_person_in_room_ignored' => true,
        'security_level' => true,
        'is_blocked' => true,
        'is_media_traceback_enabled' => true,
        'is_intervention_media_permitted' => true,
        'is_fingerprint_unfeasible' => true,
        'is_biometric_enabled' => true,
        'extended_latch_time_active' => true,
        'person_elevator_data' => true,
        'person_room_data' => true,
        'access_rights' => true,
        'profiles' => true,
        'has_individual_access_rights' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'person_id_internal' => 'PersonIdInternal',
        'is_download_enabled' => 'IsDownloadEnabled',
        'current_number_of_invalid_pin_code_entries' => 'CurrentNumberOfInvalidPinCodeEntries',
        'access_exit_date' => 'AccessExitDate',
        'last_access_date' => 'LastAccessDate',
        'last_access_grid_id' => 'LastAccessGridId',
        'last_access_domain_id' => 'LastAccessDomainId',
        'last_reader_address' => 'LastReaderAddress',
        'last_reader_name' => 'LastReaderName',
        'is_in_out_control_ignored' => 'IsInOutControlIgnored',
        'is_antipassback_ignored' => 'IsAntipassbackIgnored',
        'is_min_max_person_in_room_ignored' => 'IsMinMaxPersonInRoomIgnored',
        'security_level' => 'SecurityLevel',
        'is_blocked' => 'IsBlocked',
        'is_media_traceback_enabled' => 'IsMediaTracebackEnabled',
        'is_intervention_media_permitted' => 'IsInterventionMediaPermitted',
        'is_fingerprint_unfeasible' => 'IsFingerprintUnfeasible',
        'is_biometric_enabled' => 'IsBiometricEnabled',
        'extended_latch_time_active' => 'ExtendedLatchTimeActive',
        'person_elevator_data' => 'PersonElevatorData',
        'person_room_data' => 'PersonRoomData',
        'access_rights' => 'AccessRights',
        'profiles' => 'Profiles',
        'has_individual_access_rights' => 'HasIndividualAccessRights'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'person_id_internal' => 'setPersonIdInternal',
        'is_download_enabled' => 'setIsDownloadEnabled',
        'current_number_of_invalid_pin_code_entries' => 'setCurrentNumberOfInvalidPinCodeEntries',
        'access_exit_date' => 'setAccessExitDate',
        'last_access_date' => 'setLastAccessDate',
        'last_access_grid_id' => 'setLastAccessGridId',
        'last_access_domain_id' => 'setLastAccessDomainId',
        'last_reader_address' => 'setLastReaderAddress',
        'last_reader_name' => 'setLastReaderName',
        'is_in_out_control_ignored' => 'setIsInOutControlIgnored',
        'is_antipassback_ignored' => 'setIsAntipassbackIgnored',
        'is_min_max_person_in_room_ignored' => 'setIsMinMaxPersonInRoomIgnored',
        'security_level' => 'setSecurityLevel',
        'is_blocked' => 'setIsBlocked',
        'is_media_traceback_enabled' => 'setIsMediaTracebackEnabled',
        'is_intervention_media_permitted' => 'setIsInterventionMediaPermitted',
        'is_fingerprint_unfeasible' => 'setIsFingerprintUnfeasible',
        'is_biometric_enabled' => 'setIsBiometricEnabled',
        'extended_latch_time_active' => 'setExtendedLatchTimeActive',
        'person_elevator_data' => 'setPersonElevatorData',
        'person_room_data' => 'setPersonRoomData',
        'access_rights' => 'setAccessRights',
        'profiles' => 'setProfiles',
        'has_individual_access_rights' => 'setHasIndividualAccessRights'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'person_id_internal' => 'getPersonIdInternal',
        'is_download_enabled' => 'getIsDownloadEnabled',
        'current_number_of_invalid_pin_code_entries' => 'getCurrentNumberOfInvalidPinCodeEntries',
        'access_exit_date' => 'getAccessExitDate',
        'last_access_date' => 'getLastAccessDate',
        'last_access_grid_id' => 'getLastAccessGridId',
        'last_access_domain_id' => 'getLastAccessDomainId',
        'last_reader_address' => 'getLastReaderAddress',
        'last_reader_name' => 'getLastReaderName',
        'is_in_out_control_ignored' => 'getIsInOutControlIgnored',
        'is_antipassback_ignored' => 'getIsAntipassbackIgnored',
        'is_min_max_person_in_room_ignored' => 'getIsMinMaxPersonInRoomIgnored',
        'security_level' => 'getSecurityLevel',
        'is_blocked' => 'getIsBlocked',
        'is_media_traceback_enabled' => 'getIsMediaTracebackEnabled',
        'is_intervention_media_permitted' => 'getIsInterventionMediaPermitted',
        'is_fingerprint_unfeasible' => 'getIsFingerprintUnfeasible',
        'is_biometric_enabled' => 'getIsBiometricEnabled',
        'extended_latch_time_active' => 'getExtendedLatchTimeActive',
        'person_elevator_data' => 'getPersonElevatorData',
        'person_room_data' => 'getPersonRoomData',
        'access_rights' => 'getAccessRights',
        'profiles' => 'getProfiles',
        'has_individual_access_rights' => 'getHasIndividualAccessRights'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('person_id_internal', $data ?? [], 1);
        $this->setIfExists('is_download_enabled', $data ?? [], true);
        $this->setIfExists('current_number_of_invalid_pin_code_entries', $data ?? [], 0);
        $this->setIfExists('access_exit_date', $data ?? [], null);
        $this->setIfExists('last_access_date', $data ?? [], null);
        $this->setIfExists('last_access_grid_id', $data ?? [], 'AccessGrid 1');
        $this->setIfExists('last_access_domain_id', $data ?? [], 'AccessDomain 1');
        $this->setIfExists('last_reader_address', $data ?? [], 'E0100010001');
        $this->setIfExists('last_reader_name', $data ?? [], 'Treppenhaus 1.Stock');
        $this->setIfExists('is_in_out_control_ignored', $data ?? [], false);
        $this->setIfExists('is_antipassback_ignored', $data ?? [], false);
        $this->setIfExists('is_min_max_person_in_room_ignored', $data ?? [], false);
        $this->setIfExists('security_level', $data ?? [], 9);
        $this->setIfExists('is_blocked', $data ?? [], false);
        $this->setIfExists('is_media_traceback_enabled', $data ?? [], false);
        $this->setIfExists('is_intervention_media_permitted', $data ?? [], false);
        $this->setIfExists('is_fingerprint_unfeasible', $data ?? [], false);
        $this->setIfExists('is_biometric_enabled', $data ?? [], false);
        $this->setIfExists('extended_latch_time_active', $data ?? [], false);
        $this->setIfExists('person_elevator_data', $data ?? [], null);
        $this->setIfExists('person_room_data', $data ?? [], null);
        $this->setIfExists('access_rights', $data ?? [], null);
        $this->setIfExists('profiles', $data ?? [], null);
        $this->setIfExists('has_individual_access_rights', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['security_level']) && ($this->container['security_level'] > 9)) {
            $invalidProperties[] = "invalid value for 'security_level', must be smaller than or equal to 9.";
        }

        if (!is_null($this->container['security_level']) && ($this->container['security_level'] < 0)) {
            $invalidProperties[] = "invalid value for 'security_level', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets person_id_internal
     *
     * @return int|null
     */
    public function getPersonIdInternal()
    {
        return $this->container['person_id_internal'];
    }

    /**
     * Sets person_id_internal
     *
     * @param int|null $person_id_internal person_id_internal
     *
     * @return self
     */
    public function setPersonIdInternal($person_id_internal)
    {
        if (is_null($person_id_internal)) {
            array_push($this->openAPINullablesSetToNull, 'person_id_internal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_id_internal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_id_internal'] = $person_id_internal;

        return $this;
    }

    /**
     * Gets is_download_enabled
     *
     * @return bool|null
     */
    public function getIsDownloadEnabled()
    {
        return $this->container['is_download_enabled'];
    }

    /**
     * Sets is_download_enabled
     *
     * @param bool|null $is_download_enabled is_download_enabled
     *
     * @return self
     */
    public function setIsDownloadEnabled($is_download_enabled)
    {
        if (is_null($is_download_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'is_download_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_download_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_download_enabled'] = $is_download_enabled;

        return $this;
    }

    /**
     * Gets current_number_of_invalid_pin_code_entries
     *
     * @return int|null
     */
    public function getCurrentNumberOfInvalidPinCodeEntries()
    {
        return $this->container['current_number_of_invalid_pin_code_entries'];
    }

    /**
     * Sets current_number_of_invalid_pin_code_entries
     *
     * @param int|null $current_number_of_invalid_pin_code_entries current_number_of_invalid_pin_code_entries
     *
     * @return self
     */
    public function setCurrentNumberOfInvalidPinCodeEntries($current_number_of_invalid_pin_code_entries)
    {
        if (is_null($current_number_of_invalid_pin_code_entries)) {
            array_push($this->openAPINullablesSetToNull, 'current_number_of_invalid_pin_code_entries');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('current_number_of_invalid_pin_code_entries', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['current_number_of_invalid_pin_code_entries'] = $current_number_of_invalid_pin_code_entries;

        return $this;
    }

    /**
     * Gets access_exit_date
     *
     * @return \DateTime|null
     */
    public function getAccessExitDate()
    {
        return $this->container['access_exit_date'];
    }

    /**
     * Sets access_exit_date
     *
     * @param \DateTime|null $access_exit_date access_exit_date
     *
     * @return self
     */
    public function setAccessExitDate($access_exit_date)
    {
        if (is_null($access_exit_date)) {
            array_push($this->openAPINullablesSetToNull, 'access_exit_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('access_exit_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['access_exit_date'] = $access_exit_date;

        return $this;
    }

    /**
     * Gets last_access_date
     *
     * @return \DateTime|null
     */
    public function getLastAccessDate()
    {
        return $this->container['last_access_date'];
    }

    /**
     * Sets last_access_date
     *
     * @param \DateTime|null $last_access_date last_access_date
     *
     * @return self
     */
    public function setLastAccessDate($last_access_date)
    {
        if (is_null($last_access_date)) {
            array_push($this->openAPINullablesSetToNull, 'last_access_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_access_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_access_date'] = $last_access_date;

        return $this;
    }

    /**
     * Gets last_access_grid_id
     *
     * @return string|null
     */
    public function getLastAccessGridId()
    {
        return $this->container['last_access_grid_id'];
    }

    /**
     * Sets last_access_grid_id
     *
     * @param string|null $last_access_grid_id last_access_grid_id
     *
     * @return self
     */
    public function setLastAccessGridId($last_access_grid_id)
    {
        if (is_null($last_access_grid_id)) {
            array_push($this->openAPINullablesSetToNull, 'last_access_grid_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_access_grid_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_access_grid_id'] = $last_access_grid_id;

        return $this;
    }

    /**
     * Gets last_access_domain_id
     *
     * @return string|null
     */
    public function getLastAccessDomainId()
    {
        return $this->container['last_access_domain_id'];
    }

    /**
     * Sets last_access_domain_id
     *
     * @param string|null $last_access_domain_id last_access_domain_id
     *
     * @return self
     */
    public function setLastAccessDomainId($last_access_domain_id)
    {
        if (is_null($last_access_domain_id)) {
            array_push($this->openAPINullablesSetToNull, 'last_access_domain_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_access_domain_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_access_domain_id'] = $last_access_domain_id;

        return $this;
    }

    /**
     * Gets last_reader_address
     *
     * @return string|null
     */
    public function getLastReaderAddress()
    {
        return $this->container['last_reader_address'];
    }

    /**
     * Sets last_reader_address
     *
     * @param string|null $last_reader_address last_reader_address
     *
     * @return self
     */
    public function setLastReaderAddress($last_reader_address)
    {
        if (is_null($last_reader_address)) {
            array_push($this->openAPINullablesSetToNull, 'last_reader_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_reader_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_reader_address'] = $last_reader_address;

        return $this;
    }

    /**
     * Gets last_reader_name
     *
     * @return string|null
     */
    public function getLastReaderName()
    {
        return $this->container['last_reader_name'];
    }

    /**
     * Sets last_reader_name
     *
     * @param string|null $last_reader_name last_reader_name
     *
     * @return self
     */
    public function setLastReaderName($last_reader_name)
    {
        if (is_null($last_reader_name)) {
            array_push($this->openAPINullablesSetToNull, 'last_reader_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_reader_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_reader_name'] = $last_reader_name;

        return $this;
    }

    /**
     * Gets is_in_out_control_ignored
     *
     * @return bool|null
     */
    public function getIsInOutControlIgnored()
    {
        return $this->container['is_in_out_control_ignored'];
    }

    /**
     * Sets is_in_out_control_ignored
     *
     * @param bool|null $is_in_out_control_ignored is_in_out_control_ignored
     *
     * @return self
     */
    public function setIsInOutControlIgnored($is_in_out_control_ignored)
    {
        if (is_null($is_in_out_control_ignored)) {
            array_push($this->openAPINullablesSetToNull, 'is_in_out_control_ignored');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_in_out_control_ignored', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_in_out_control_ignored'] = $is_in_out_control_ignored;

        return $this;
    }

    /**
     * Gets is_antipassback_ignored
     *
     * @return bool|null
     */
    public function getIsAntipassbackIgnored()
    {
        return $this->container['is_antipassback_ignored'];
    }

    /**
     * Sets is_antipassback_ignored
     *
     * @param bool|null $is_antipassback_ignored is_antipassback_ignored
     *
     * @return self
     */
    public function setIsAntipassbackIgnored($is_antipassback_ignored)
    {
        if (is_null($is_antipassback_ignored)) {
            array_push($this->openAPINullablesSetToNull, 'is_antipassback_ignored');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_antipassback_ignored', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_antipassback_ignored'] = $is_antipassback_ignored;

        return $this;
    }

    /**
     * Gets is_min_max_person_in_room_ignored
     *
     * @return bool|null
     */
    public function getIsMinMaxPersonInRoomIgnored()
    {
        return $this->container['is_min_max_person_in_room_ignored'];
    }

    /**
     * Sets is_min_max_person_in_room_ignored
     *
     * @param bool|null $is_min_max_person_in_room_ignored is_min_max_person_in_room_ignored
     *
     * @return self
     */
    public function setIsMinMaxPersonInRoomIgnored($is_min_max_person_in_room_ignored)
    {
        if (is_null($is_min_max_person_in_room_ignored)) {
            array_push($this->openAPINullablesSetToNull, 'is_min_max_person_in_room_ignored');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_min_max_person_in_room_ignored', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_min_max_person_in_room_ignored'] = $is_min_max_person_in_room_ignored;

        return $this;
    }

    /**
     * Gets security_level
     *
     * @return int|null
     */
    public function getSecurityLevel()
    {
        return $this->container['security_level'];
    }

    /**
     * Sets security_level
     *
     * @param int|null $security_level security_level
     *
     * @return self
     */
    public function setSecurityLevel($security_level)
    {
        if (is_null($security_level)) {
            array_push($this->openAPINullablesSetToNull, 'security_level');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('security_level', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($security_level) && ($security_level > 9)) {
            throw new \InvalidArgumentException('invalid value for $security_level when calling PersonAccessControlDataOutput., must be smaller than or equal to 9.');
        }
        if (!is_null($security_level) && ($security_level < 0)) {
            throw new \InvalidArgumentException('invalid value for $security_level when calling PersonAccessControlDataOutput., must be bigger than or equal to 0.');
        }

        $this->container['security_level'] = $security_level;

        return $this;
    }

    /**
     * Gets is_blocked
     *
     * @return bool|null
     */
    public function getIsBlocked()
    {
        return $this->container['is_blocked'];
    }

    /**
     * Sets is_blocked
     *
     * @param bool|null $is_blocked is_blocked
     *
     * @return self
     */
    public function setIsBlocked($is_blocked)
    {
        if (is_null($is_blocked)) {
            array_push($this->openAPINullablesSetToNull, 'is_blocked');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_blocked', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_blocked'] = $is_blocked;

        return $this;
    }

    /**
     * Gets is_media_traceback_enabled
     *
     * @return bool|null
     */
    public function getIsMediaTracebackEnabled()
    {
        return $this->container['is_media_traceback_enabled'];
    }

    /**
     * Sets is_media_traceback_enabled
     *
     * @param bool|null $is_media_traceback_enabled is_media_traceback_enabled
     *
     * @return self
     */
    public function setIsMediaTracebackEnabled($is_media_traceback_enabled)
    {
        if (is_null($is_media_traceback_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'is_media_traceback_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_media_traceback_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_media_traceback_enabled'] = $is_media_traceback_enabled;

        return $this;
    }

    /**
     * Gets is_intervention_media_permitted
     *
     * @return bool|null
     */
    public function getIsInterventionMediaPermitted()
    {
        return $this->container['is_intervention_media_permitted'];
    }

    /**
     * Sets is_intervention_media_permitted
     *
     * @param bool|null $is_intervention_media_permitted is_intervention_media_permitted
     *
     * @return self
     */
    public function setIsInterventionMediaPermitted($is_intervention_media_permitted)
    {
        if (is_null($is_intervention_media_permitted)) {
            array_push($this->openAPINullablesSetToNull, 'is_intervention_media_permitted');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_intervention_media_permitted', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_intervention_media_permitted'] = $is_intervention_media_permitted;

        return $this;
    }

    /**
     * Gets is_fingerprint_unfeasible
     *
     * @return bool|null
     */
    public function getIsFingerprintUnfeasible()
    {
        return $this->container['is_fingerprint_unfeasible'];
    }

    /**
     * Sets is_fingerprint_unfeasible
     *
     * @param bool|null $is_fingerprint_unfeasible is_fingerprint_unfeasible
     *
     * @return self
     */
    public function setIsFingerprintUnfeasible($is_fingerprint_unfeasible)
    {
        if (is_null($is_fingerprint_unfeasible)) {
            array_push($this->openAPINullablesSetToNull, 'is_fingerprint_unfeasible');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_fingerprint_unfeasible', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_fingerprint_unfeasible'] = $is_fingerprint_unfeasible;

        return $this;
    }

    /**
     * Gets is_biometric_enabled
     *
     * @return bool|null
     */
    public function getIsBiometricEnabled()
    {
        return $this->container['is_biometric_enabled'];
    }

    /**
     * Sets is_biometric_enabled
     *
     * @param bool|null $is_biometric_enabled is_biometric_enabled
     *
     * @return self
     */
    public function setIsBiometricEnabled($is_biometric_enabled)
    {
        if (is_null($is_biometric_enabled)) {
            array_push($this->openAPINullablesSetToNull, 'is_biometric_enabled');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_biometric_enabled', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_biometric_enabled'] = $is_biometric_enabled;

        return $this;
    }

    /**
     * Gets extended_latch_time_active
     *
     * @return bool|null
     */
    public function getExtendedLatchTimeActive()
    {
        return $this->container['extended_latch_time_active'];
    }

    /**
     * Sets extended_latch_time_active
     *
     * @param bool|null $extended_latch_time_active extended_latch_time_active
     *
     * @return self
     */
    public function setExtendedLatchTimeActive($extended_latch_time_active)
    {
        if (is_null($extended_latch_time_active)) {
            array_push($this->openAPINullablesSetToNull, 'extended_latch_time_active');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('extended_latch_time_active', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['extended_latch_time_active'] = $extended_latch_time_active;

        return $this;
    }

    /**
     * Gets person_elevator_data
     *
     * @return \Exos\ExosApi\Model\PersonElevatorDataOutput|null
     */
    public function getPersonElevatorData()
    {
        return $this->container['person_elevator_data'];
    }

    /**
     * Sets person_elevator_data
     *
     * @param \Exos\ExosApi\Model\PersonElevatorDataOutput|null $person_elevator_data person_elevator_data
     *
     * @return self
     */
    public function setPersonElevatorData($person_elevator_data)
    {
        if (is_null($person_elevator_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_elevator_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_elevator_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_elevator_data'] = $person_elevator_data;

        return $this;
    }

    /**
     * Gets person_room_data
     *
     * @return \Exos\ExosApi\Model\PersonRoomData|null
     */
    public function getPersonRoomData()
    {
        return $this->container['person_room_data'];
    }

    /**
     * Sets person_room_data
     *
     * @param \Exos\ExosApi\Model\PersonRoomData|null $person_room_data person_room_data
     *
     * @return self
     */
    public function setPersonRoomData($person_room_data)
    {
        if (is_null($person_room_data)) {
            array_push($this->openAPINullablesSetToNull, 'person_room_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_room_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_room_data'] = $person_room_data;

        return $this;
    }

    /**
     * Gets access_rights
     *
     * @return \Exos\ExosApi\Model\PersonAccessRights[]|null
     */
    public function getAccessRights()
    {
        return $this->container['access_rights'];
    }

    /**
     * Sets access_rights
     *
     * @param \Exos\ExosApi\Model\PersonAccessRights[]|null $access_rights access_rights
     *
     * @return self
     */
    public function setAccessRights($access_rights)
    {
        if (is_null($access_rights)) {
            array_push($this->openAPINullablesSetToNull, 'access_rights');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('access_rights', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['access_rights'] = $access_rights;

        return $this;
    }

    /**
     * Gets profiles
     *
     * @return \Exos\ExosApi\Model\PersonProfiles[]|null
     */
    public function getProfiles()
    {
        return $this->container['profiles'];
    }

    /**
     * Sets profiles
     *
     * @param \Exos\ExosApi\Model\PersonProfiles[]|null $profiles profiles
     *
     * @return self
     */
    public function setProfiles($profiles)
    {
        if (is_null($profiles)) {
            array_push($this->openAPINullablesSetToNull, 'profiles');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('profiles', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['profiles'] = $profiles;

        return $this;
    }

    /**
     * Gets has_individual_access_rights
     *
     * @return \Exos\ExosApi\Model\PersonHasIndividualAccessRights[]|null
     */
    public function getHasIndividualAccessRights()
    {
        return $this->container['has_individual_access_rights'];
    }

    /**
     * Sets has_individual_access_rights
     *
     * @param \Exos\ExosApi\Model\PersonHasIndividualAccessRights[]|null $has_individual_access_rights has_individual_access_rights
     *
     * @return self
     */
    public function setHasIndividualAccessRights($has_individual_access_rights)
    {
        if (is_null($has_individual_access_rights)) {
            array_push($this->openAPINullablesSetToNull, 'has_individual_access_rights');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('has_individual_access_rights', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['has_individual_access_rights'] = $has_individual_access_rights;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


