<?php
/**
 * UpdateVisitInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * UpdateVisitInput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateVisitInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateVisitInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'visit_id' => 'string',
        'start_time' => '\DateTime',
        'end_time' => '\DateTime',
        'subject' => 'string',
        'info' => 'string',
        'anonymous_members' => 'int',
        'kabacard_layout' => 'string',
        'host_id' => 'string',
        'deputy_id' => 'string',
        'location_id' => 'string',
        'workstation_id' => 'string',
        'text1' => 'string',
        'text2' => 'string',
        'text3' => 'string',
        'text4' => 'string',
        'text5' => 'string',
        'text6' => 'string',
        'text7' => 'string',
        'text8' => 'string',
        'text9' => 'string',
        'text10' => 'string',
        'number1' => 'int',
        'number2' => 'int',
        'number3' => 'int',
        'number4' => 'int',
        'number5' => 'int',
        'bool1' => 'bool',
        'bool2' => 'bool',
        'bool3' => 'bool',
        'bool4' => 'bool',
        'bool5' => 'bool',
        'date1' => '\DateTime',
        'date2' => '\DateTime',
        'date3' => '\DateTime',
        'date4' => '\DateTime',
        'date5' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'visit_id' => null,
        'start_time' => 'date-time',
        'end_time' => 'date-time',
        'subject' => null,
        'info' => null,
        'anonymous_members' => 'int32',
        'kabacard_layout' => null,
        'host_id' => null,
        'deputy_id' => null,
        'location_id' => null,
        'workstation_id' => null,
        'text1' => null,
        'text2' => null,
        'text3' => null,
        'text4' => null,
        'text5' => null,
        'text6' => null,
        'text7' => null,
        'text8' => null,
        'text9' => null,
        'text10' => null,
        'number1' => 'int32',
        'number2' => 'int32',
        'number3' => 'int32',
        'number4' => 'int32',
        'number5' => 'int32',
        'bool1' => null,
        'bool2' => null,
        'bool3' => null,
        'bool4' => null,
        'bool5' => null,
        'date1' => 'date-time',
        'date2' => 'date-time',
        'date3' => 'date-time',
        'date4' => 'date-time',
        'date5' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'visit_id' => true,
        'start_time' => true,
        'end_time' => true,
        'subject' => true,
        'info' => true,
        'anonymous_members' => true,
        'kabacard_layout' => true,
        'host_id' => true,
        'deputy_id' => true,
        'location_id' => true,
        'workstation_id' => true,
        'text1' => true,
        'text2' => true,
        'text3' => true,
        'text4' => true,
        'text5' => true,
        'text6' => true,
        'text7' => true,
        'text8' => true,
        'text9' => true,
        'text10' => true,
        'number1' => true,
        'number2' => true,
        'number3' => true,
        'number4' => true,
        'number5' => true,
        'bool1' => true,
        'bool2' => true,
        'bool3' => true,
        'bool4' => true,
        'bool5' => true,
        'date1' => true,
        'date2' => true,
        'date3' => true,
        'date4' => true,
        'date5' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'visit_id' => 'VisitId',
        'start_time' => 'StartTime',
        'end_time' => 'EndTime',
        'subject' => 'Subject',
        'info' => 'Info',
        'anonymous_members' => 'AnonymousMembers',
        'kabacard_layout' => 'KabacardLayout',
        'host_id' => 'HostId',
        'deputy_id' => 'DeputyId',
        'location_id' => 'LocationId',
        'workstation_id' => 'WorkstationId',
        'text1' => 'Text1',
        'text2' => 'Text2',
        'text3' => 'Text3',
        'text4' => 'Text4',
        'text5' => 'Text5',
        'text6' => 'Text6',
        'text7' => 'Text7',
        'text8' => 'Text8',
        'text9' => 'Text9',
        'text10' => 'Text10',
        'number1' => 'Number1',
        'number2' => 'Number2',
        'number3' => 'Number3',
        'number4' => 'Number4',
        'number5' => 'Number5',
        'bool1' => 'Bool1',
        'bool2' => 'Bool2',
        'bool3' => 'Bool3',
        'bool4' => 'Bool4',
        'bool5' => 'Bool5',
        'date1' => 'Date1',
        'date2' => 'Date2',
        'date3' => 'Date3',
        'date4' => 'Date4',
        'date5' => 'Date5'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'visit_id' => 'setVisitId',
        'start_time' => 'setStartTime',
        'end_time' => 'setEndTime',
        'subject' => 'setSubject',
        'info' => 'setInfo',
        'anonymous_members' => 'setAnonymousMembers',
        'kabacard_layout' => 'setKabacardLayout',
        'host_id' => 'setHostId',
        'deputy_id' => 'setDeputyId',
        'location_id' => 'setLocationId',
        'workstation_id' => 'setWorkstationId',
        'text1' => 'setText1',
        'text2' => 'setText2',
        'text3' => 'setText3',
        'text4' => 'setText4',
        'text5' => 'setText5',
        'text6' => 'setText6',
        'text7' => 'setText7',
        'text8' => 'setText8',
        'text9' => 'setText9',
        'text10' => 'setText10',
        'number1' => 'setNumber1',
        'number2' => 'setNumber2',
        'number3' => 'setNumber3',
        'number4' => 'setNumber4',
        'number5' => 'setNumber5',
        'bool1' => 'setBool1',
        'bool2' => 'setBool2',
        'bool3' => 'setBool3',
        'bool4' => 'setBool4',
        'bool5' => 'setBool5',
        'date1' => 'setDate1',
        'date2' => 'setDate2',
        'date3' => 'setDate3',
        'date4' => 'setDate4',
        'date5' => 'setDate5'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'visit_id' => 'getVisitId',
        'start_time' => 'getStartTime',
        'end_time' => 'getEndTime',
        'subject' => 'getSubject',
        'info' => 'getInfo',
        'anonymous_members' => 'getAnonymousMembers',
        'kabacard_layout' => 'getKabacardLayout',
        'host_id' => 'getHostId',
        'deputy_id' => 'getDeputyId',
        'location_id' => 'getLocationId',
        'workstation_id' => 'getWorkstationId',
        'text1' => 'getText1',
        'text2' => 'getText2',
        'text3' => 'getText3',
        'text4' => 'getText4',
        'text5' => 'getText5',
        'text6' => 'getText6',
        'text7' => 'getText7',
        'text8' => 'getText8',
        'text9' => 'getText9',
        'text10' => 'getText10',
        'number1' => 'getNumber1',
        'number2' => 'getNumber2',
        'number3' => 'getNumber3',
        'number4' => 'getNumber4',
        'number5' => 'getNumber5',
        'bool1' => 'getBool1',
        'bool2' => 'getBool2',
        'bool3' => 'getBool3',
        'bool4' => 'getBool4',
        'bool5' => 'getBool5',
        'date1' => 'getDate1',
        'date2' => 'getDate2',
        'date3' => 'getDate3',
        'date4' => 'getDate4',
        'date5' => 'getDate5'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('visit_id', $data ?? [], '');
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], '');
        $this->setIfExists('info', $data ?? [], '');
        $this->setIfExists('anonymous_members', $data ?? [], null);
        $this->setIfExists('kabacard_layout', $data ?? [], '');
        $this->setIfExists('host_id', $data ?? [], '');
        $this->setIfExists('deputy_id', $data ?? [], '');
        $this->setIfExists('location_id', $data ?? [], '');
        $this->setIfExists('workstation_id', $data ?? [], '');
        $this->setIfExists('text1', $data ?? [], '');
        $this->setIfExists('text2', $data ?? [], '');
        $this->setIfExists('text3', $data ?? [], '');
        $this->setIfExists('text4', $data ?? [], '');
        $this->setIfExists('text5', $data ?? [], '');
        $this->setIfExists('text6', $data ?? [], '');
        $this->setIfExists('text7', $data ?? [], '');
        $this->setIfExists('text8', $data ?? [], '');
        $this->setIfExists('text9', $data ?? [], '');
        $this->setIfExists('text10', $data ?? [], '');
        $this->setIfExists('number1', $data ?? [], 0);
        $this->setIfExists('number2', $data ?? [], 0);
        $this->setIfExists('number3', $data ?? [], 0);
        $this->setIfExists('number4', $data ?? [], 0);
        $this->setIfExists('number5', $data ?? [], 0);
        $this->setIfExists('bool1', $data ?? [], false);
        $this->setIfExists('bool2', $data ?? [], false);
        $this->setIfExists('bool3', $data ?? [], false);
        $this->setIfExists('bool4', $data ?? [], false);
        $this->setIfExists('bool5', $data ?? [], false);
        $this->setIfExists('date1', $data ?? [], null);
        $this->setIfExists('date2', $data ?? [], null);
        $this->setIfExists('date3', $data ?? [], null);
        $this->setIfExists('date4', $data ?? [], null);
        $this->setIfExists('date5', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets visit_id
     *
     * @return string|null
     */
    public function getVisitId()
    {
        return $this->container['visit_id'];
    }

    /**
     * Sets visit_id
     *
     * @param string|null $visit_id visit_id
     *
     * @return self
     */
    public function setVisitId($visit_id)
    {
        if (is_null($visit_id)) {
            array_push($this->openAPINullablesSetToNull, 'visit_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('visit_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['visit_id'] = $visit_id;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return \DateTime|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param \DateTime|null $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            array_push($this->openAPINullablesSetToNull, 'start_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return \DateTime|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param \DateTime|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            array_push($this->openAPINullablesSetToNull, 'end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            array_push($this->openAPINullablesSetToNull, 'subject');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subject', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets info
     *
     * @return string|null
     */
    public function getInfo()
    {
        return $this->container['info'];
    }

    /**
     * Sets info
     *
     * @param string|null $info info
     *
     * @return self
     */
    public function setInfo($info)
    {
        if (is_null($info)) {
            array_push($this->openAPINullablesSetToNull, 'info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('info', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['info'] = $info;

        return $this;
    }

    /**
     * Gets anonymous_members
     *
     * @return int|null
     */
    public function getAnonymousMembers()
    {
        return $this->container['anonymous_members'];
    }

    /**
     * Sets anonymous_members
     *
     * @param int|null $anonymous_members anonymous_members
     *
     * @return self
     */
    public function setAnonymousMembers($anonymous_members)
    {
        if (is_null($anonymous_members)) {
            array_push($this->openAPINullablesSetToNull, 'anonymous_members');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('anonymous_members', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['anonymous_members'] = $anonymous_members;

        return $this;
    }

    /**
     * Gets kabacard_layout
     *
     * @return string|null
     */
    public function getKabacardLayout()
    {
        return $this->container['kabacard_layout'];
    }

    /**
     * Sets kabacard_layout
     *
     * @param string|null $kabacard_layout kabacard_layout
     *
     * @return self
     */
    public function setKabacardLayout($kabacard_layout)
    {
        if (is_null($kabacard_layout)) {
            array_push($this->openAPINullablesSetToNull, 'kabacard_layout');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('kabacard_layout', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['kabacard_layout'] = $kabacard_layout;

        return $this;
    }

    /**
     * Gets host_id
     *
     * @return string|null
     */
    public function getHostId()
    {
        return $this->container['host_id'];
    }

    /**
     * Sets host_id
     *
     * @param string|null $host_id host_id
     *
     * @return self
     */
    public function setHostId($host_id)
    {
        if (is_null($host_id)) {
            array_push($this->openAPINullablesSetToNull, 'host_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('host_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['host_id'] = $host_id;

        return $this;
    }

    /**
     * Gets deputy_id
     *
     * @return string|null
     */
    public function getDeputyId()
    {
        return $this->container['deputy_id'];
    }

    /**
     * Sets deputy_id
     *
     * @param string|null $deputy_id deputy_id
     *
     * @return self
     */
    public function setDeputyId($deputy_id)
    {
        if (is_null($deputy_id)) {
            array_push($this->openAPINullablesSetToNull, 'deputy_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deputy_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deputy_id'] = $deputy_id;

        return $this;
    }

    /**
     * Gets location_id
     *
     * @return string|null
     */
    public function getLocationId()
    {
        return $this->container['location_id'];
    }

    /**
     * Sets location_id
     *
     * @param string|null $location_id location_id
     *
     * @return self
     */
    public function setLocationId($location_id)
    {
        if (is_null($location_id)) {
            array_push($this->openAPINullablesSetToNull, 'location_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['location_id'] = $location_id;

        return $this;
    }

    /**
     * Gets workstation_id
     *
     * @return string|null
     */
    public function getWorkstationId()
    {
        return $this->container['workstation_id'];
    }

    /**
     * Sets workstation_id
     *
     * @param string|null $workstation_id workstation_id
     *
     * @return self
     */
    public function setWorkstationId($workstation_id)
    {
        if (is_null($workstation_id)) {
            array_push($this->openAPINullablesSetToNull, 'workstation_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('workstation_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['workstation_id'] = $workstation_id;

        return $this;
    }

    /**
     * Gets text1
     *
     * @return string|null
     */
    public function getText1()
    {
        return $this->container['text1'];
    }

    /**
     * Sets text1
     *
     * @param string|null $text1 text1
     *
     * @return self
     */
    public function setText1($text1)
    {
        if (is_null($text1)) {
            array_push($this->openAPINullablesSetToNull, 'text1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text1'] = $text1;

        return $this;
    }

    /**
     * Gets text2
     *
     * @return string|null
     */
    public function getText2()
    {
        return $this->container['text2'];
    }

    /**
     * Sets text2
     *
     * @param string|null $text2 text2
     *
     * @return self
     */
    public function setText2($text2)
    {
        if (is_null($text2)) {
            array_push($this->openAPINullablesSetToNull, 'text2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text2'] = $text2;

        return $this;
    }

    /**
     * Gets text3
     *
     * @return string|null
     */
    public function getText3()
    {
        return $this->container['text3'];
    }

    /**
     * Sets text3
     *
     * @param string|null $text3 text3
     *
     * @return self
     */
    public function setText3($text3)
    {
        if (is_null($text3)) {
            array_push($this->openAPINullablesSetToNull, 'text3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text3'] = $text3;

        return $this;
    }

    /**
     * Gets text4
     *
     * @return string|null
     */
    public function getText4()
    {
        return $this->container['text4'];
    }

    /**
     * Sets text4
     *
     * @param string|null $text4 text4
     *
     * @return self
     */
    public function setText4($text4)
    {
        if (is_null($text4)) {
            array_push($this->openAPINullablesSetToNull, 'text4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text4'] = $text4;

        return $this;
    }

    /**
     * Gets text5
     *
     * @return string|null
     */
    public function getText5()
    {
        return $this->container['text5'];
    }

    /**
     * Sets text5
     *
     * @param string|null $text5 text5
     *
     * @return self
     */
    public function setText5($text5)
    {
        if (is_null($text5)) {
            array_push($this->openAPINullablesSetToNull, 'text5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text5'] = $text5;

        return $this;
    }

    /**
     * Gets text6
     *
     * @return string|null
     */
    public function getText6()
    {
        return $this->container['text6'];
    }

    /**
     * Sets text6
     *
     * @param string|null $text6 text6
     *
     * @return self
     */
    public function setText6($text6)
    {
        if (is_null($text6)) {
            array_push($this->openAPINullablesSetToNull, 'text6');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text6', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text6'] = $text6;

        return $this;
    }

    /**
     * Gets text7
     *
     * @return string|null
     */
    public function getText7()
    {
        return $this->container['text7'];
    }

    /**
     * Sets text7
     *
     * @param string|null $text7 text7
     *
     * @return self
     */
    public function setText7($text7)
    {
        if (is_null($text7)) {
            array_push($this->openAPINullablesSetToNull, 'text7');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text7', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text7'] = $text7;

        return $this;
    }

    /**
     * Gets text8
     *
     * @return string|null
     */
    public function getText8()
    {
        return $this->container['text8'];
    }

    /**
     * Sets text8
     *
     * @param string|null $text8 text8
     *
     * @return self
     */
    public function setText8($text8)
    {
        if (is_null($text8)) {
            array_push($this->openAPINullablesSetToNull, 'text8');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text8', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text8'] = $text8;

        return $this;
    }

    /**
     * Gets text9
     *
     * @return string|null
     */
    public function getText9()
    {
        return $this->container['text9'];
    }

    /**
     * Sets text9
     *
     * @param string|null $text9 text9
     *
     * @return self
     */
    public function setText9($text9)
    {
        if (is_null($text9)) {
            array_push($this->openAPINullablesSetToNull, 'text9');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text9', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text9'] = $text9;

        return $this;
    }

    /**
     * Gets text10
     *
     * @return string|null
     */
    public function getText10()
    {
        return $this->container['text10'];
    }

    /**
     * Sets text10
     *
     * @param string|null $text10 text10
     *
     * @return self
     */
    public function setText10($text10)
    {
        if (is_null($text10)) {
            array_push($this->openAPINullablesSetToNull, 'text10');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text10', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text10'] = $text10;

        return $this;
    }

    /**
     * Gets number1
     *
     * @return int|null
     */
    public function getNumber1()
    {
        return $this->container['number1'];
    }

    /**
     * Sets number1
     *
     * @param int|null $number1 number1
     *
     * @return self
     */
    public function setNumber1($number1)
    {
        if (is_null($number1)) {
            array_push($this->openAPINullablesSetToNull, 'number1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number1'] = $number1;

        return $this;
    }

    /**
     * Gets number2
     *
     * @return int|null
     */
    public function getNumber2()
    {
        return $this->container['number2'];
    }

    /**
     * Sets number2
     *
     * @param int|null $number2 number2
     *
     * @return self
     */
    public function setNumber2($number2)
    {
        if (is_null($number2)) {
            array_push($this->openAPINullablesSetToNull, 'number2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number2'] = $number2;

        return $this;
    }

    /**
     * Gets number3
     *
     * @return int|null
     */
    public function getNumber3()
    {
        return $this->container['number3'];
    }

    /**
     * Sets number3
     *
     * @param int|null $number3 number3
     *
     * @return self
     */
    public function setNumber3($number3)
    {
        if (is_null($number3)) {
            array_push($this->openAPINullablesSetToNull, 'number3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number3'] = $number3;

        return $this;
    }

    /**
     * Gets number4
     *
     * @return int|null
     */
    public function getNumber4()
    {
        return $this->container['number4'];
    }

    /**
     * Sets number4
     *
     * @param int|null $number4 number4
     *
     * @return self
     */
    public function setNumber4($number4)
    {
        if (is_null($number4)) {
            array_push($this->openAPINullablesSetToNull, 'number4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number4'] = $number4;

        return $this;
    }

    /**
     * Gets number5
     *
     * @return int|null
     */
    public function getNumber5()
    {
        return $this->container['number5'];
    }

    /**
     * Sets number5
     *
     * @param int|null $number5 number5
     *
     * @return self
     */
    public function setNumber5($number5)
    {
        if (is_null($number5)) {
            array_push($this->openAPINullablesSetToNull, 'number5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number5'] = $number5;

        return $this;
    }

    /**
     * Gets bool1
     *
     * @return bool|null
     */
    public function getBool1()
    {
        return $this->container['bool1'];
    }

    /**
     * Sets bool1
     *
     * @param bool|null $bool1 bool1
     *
     * @return self
     */
    public function setBool1($bool1)
    {
        if (is_null($bool1)) {
            array_push($this->openAPINullablesSetToNull, 'bool1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool1'] = $bool1;

        return $this;
    }

    /**
     * Gets bool2
     *
     * @return bool|null
     */
    public function getBool2()
    {
        return $this->container['bool2'];
    }

    /**
     * Sets bool2
     *
     * @param bool|null $bool2 bool2
     *
     * @return self
     */
    public function setBool2($bool2)
    {
        if (is_null($bool2)) {
            array_push($this->openAPINullablesSetToNull, 'bool2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool2'] = $bool2;

        return $this;
    }

    /**
     * Gets bool3
     *
     * @return bool|null
     */
    public function getBool3()
    {
        return $this->container['bool3'];
    }

    /**
     * Sets bool3
     *
     * @param bool|null $bool3 bool3
     *
     * @return self
     */
    public function setBool3($bool3)
    {
        if (is_null($bool3)) {
            array_push($this->openAPINullablesSetToNull, 'bool3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool3'] = $bool3;

        return $this;
    }

    /**
     * Gets bool4
     *
     * @return bool|null
     */
    public function getBool4()
    {
        return $this->container['bool4'];
    }

    /**
     * Sets bool4
     *
     * @param bool|null $bool4 bool4
     *
     * @return self
     */
    public function setBool4($bool4)
    {
        if (is_null($bool4)) {
            array_push($this->openAPINullablesSetToNull, 'bool4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool4'] = $bool4;

        return $this;
    }

    /**
     * Gets bool5
     *
     * @return bool|null
     */
    public function getBool5()
    {
        return $this->container['bool5'];
    }

    /**
     * Sets bool5
     *
     * @param bool|null $bool5 bool5
     *
     * @return self
     */
    public function setBool5($bool5)
    {
        if (is_null($bool5)) {
            array_push($this->openAPINullablesSetToNull, 'bool5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool5'] = $bool5;

        return $this;
    }

    /**
     * Gets date1
     *
     * @return \DateTime|null
     */
    public function getDate1()
    {
        return $this->container['date1'];
    }

    /**
     * Sets date1
     *
     * @param \DateTime|null $date1 date1
     *
     * @return self
     */
    public function setDate1($date1)
    {
        if (is_null($date1)) {
            array_push($this->openAPINullablesSetToNull, 'date1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date1'] = $date1;

        return $this;
    }

    /**
     * Gets date2
     *
     * @return \DateTime|null
     */
    public function getDate2()
    {
        return $this->container['date2'];
    }

    /**
     * Sets date2
     *
     * @param \DateTime|null $date2 date2
     *
     * @return self
     */
    public function setDate2($date2)
    {
        if (is_null($date2)) {
            array_push($this->openAPINullablesSetToNull, 'date2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date2'] = $date2;

        return $this;
    }

    /**
     * Gets date3
     *
     * @return \DateTime|null
     */
    public function getDate3()
    {
        return $this->container['date3'];
    }

    /**
     * Sets date3
     *
     * @param \DateTime|null $date3 date3
     *
     * @return self
     */
    public function setDate3($date3)
    {
        if (is_null($date3)) {
            array_push($this->openAPINullablesSetToNull, 'date3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date3'] = $date3;

        return $this;
    }

    /**
     * Gets date4
     *
     * @return \DateTime|null
     */
    public function getDate4()
    {
        return $this->container['date4'];
    }

    /**
     * Sets date4
     *
     * @param \DateTime|null $date4 date4
     *
     * @return self
     */
    public function setDate4($date4)
    {
        if (is_null($date4)) {
            array_push($this->openAPINullablesSetToNull, 'date4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date4'] = $date4;

        return $this;
    }

    /**
     * Gets date5
     *
     * @return \DateTime|null
     */
    public function getDate5()
    {
        return $this->container['date5'];
    }

    /**
     * Sets date5
     *
     * @param \DateTime|null $date5 date5
     *
     * @return self
     */
    public function setDate5($date5)
    {
        if (is_null($date5)) {
            array_push($this->openAPINullablesSetToNull, 'date5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date5'] = $date5;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


