<?php
/**
 * UpdateHierarchyInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * exos API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.4.01
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Exos\ExosApi\Model;

use \ArrayAccess;
use \Exos\ExosApi\ObjectSerializer;

/**
 * UpdateHierarchyInput Class Doc Comment
 *
 * @category Class
 * @package  Exos\ExosApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateHierarchyInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateHierarchyInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'hierarchy_name' => 'string',
        'type' => '\Exos\ExosApi\Model\HierarchyType',
        'hierarchy_id' => 'string',
        'person_category_id_internal' => 'int',
        'street' => 'string',
        'po_box' => 'string',
        'zip' => 'string',
        'city' => 'string',
        'country' => 'string',
        'phone' => 'string',
        'fax' => 'string',
        'e_mail' => 'string',
        'commentary' => 'string',
        'text1' => 'string',
        'text2' => 'string',
        'text3' => 'string',
        'text4' => 'string',
        'text5' => 'string',
        'text6' => 'string',
        'text7' => 'string',
        'text8' => 'string',
        'text9' => 'string',
        'text10' => 'string',
        'date1' => '\DateTime',
        'date2' => '\DateTime',
        'date3' => '\DateTime',
        'date4' => '\DateTime',
        'date5' => '\DateTime',
        'bool1' => 'bool',
        'bool2' => 'bool',
        'bool3' => 'bool',
        'bool4' => 'bool',
        'bool5' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'hierarchy_name' => null,
        'type' => null,
        'hierarchy_id' => null,
        'person_category_id_internal' => 'int32',
        'street' => null,
        'po_box' => null,
        'zip' => null,
        'city' => null,
        'country' => null,
        'phone' => null,
        'fax' => null,
        'e_mail' => null,
        'commentary' => null,
        'text1' => null,
        'text2' => null,
        'text3' => null,
        'text4' => null,
        'text5' => null,
        'text6' => null,
        'text7' => null,
        'text8' => null,
        'text9' => null,
        'text10' => null,
        'date1' => 'date-time',
        'date2' => 'date-time',
        'date3' => 'date-time',
        'date4' => 'date-time',
        'date5' => 'date-time',
        'bool1' => null,
        'bool2' => null,
        'bool3' => null,
        'bool4' => null,
        'bool5' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'hierarchy_name' => false,
        'type' => true,
        'hierarchy_id' => true,
        'person_category_id_internal' => true,
        'street' => true,
        'po_box' => true,
        'zip' => true,
        'city' => true,
        'country' => true,
        'phone' => true,
        'fax' => true,
        'e_mail' => true,
        'commentary' => true,
        'text1' => true,
        'text2' => true,
        'text3' => true,
        'text4' => true,
        'text5' => true,
        'text6' => true,
        'text7' => true,
        'text8' => true,
        'text9' => true,
        'text10' => true,
        'date1' => true,
        'date2' => true,
        'date3' => true,
        'date4' => true,
        'date5' => true,
        'bool1' => true,
        'bool2' => true,
        'bool3' => true,
        'bool4' => true,
        'bool5' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hierarchy_name' => 'HierarchyName',
        'type' => 'Type',
        'hierarchy_id' => 'HierarchyId',
        'person_category_id_internal' => 'PersonCategoryIdInternal',
        'street' => 'Street',
        'po_box' => 'PoBox',
        'zip' => 'Zip',
        'city' => 'City',
        'country' => 'Country',
        'phone' => 'Phone',
        'fax' => 'Fax',
        'e_mail' => 'EMail',
        'commentary' => 'Commentary',
        'text1' => 'Text1',
        'text2' => 'Text2',
        'text3' => 'Text3',
        'text4' => 'Text4',
        'text5' => 'Text5',
        'text6' => 'Text6',
        'text7' => 'Text7',
        'text8' => 'Text8',
        'text9' => 'Text9',
        'text10' => 'Text10',
        'date1' => 'Date1',
        'date2' => 'Date2',
        'date3' => 'Date3',
        'date4' => 'Date4',
        'date5' => 'Date5',
        'bool1' => 'Bool1',
        'bool2' => 'Bool2',
        'bool3' => 'Bool3',
        'bool4' => 'Bool4',
        'bool5' => 'Bool5'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hierarchy_name' => 'setHierarchyName',
        'type' => 'setType',
        'hierarchy_id' => 'setHierarchyId',
        'person_category_id_internal' => 'setPersonCategoryIdInternal',
        'street' => 'setStreet',
        'po_box' => 'setPoBox',
        'zip' => 'setZip',
        'city' => 'setCity',
        'country' => 'setCountry',
        'phone' => 'setPhone',
        'fax' => 'setFax',
        'e_mail' => 'setEMail',
        'commentary' => 'setCommentary',
        'text1' => 'setText1',
        'text2' => 'setText2',
        'text3' => 'setText3',
        'text4' => 'setText4',
        'text5' => 'setText5',
        'text6' => 'setText6',
        'text7' => 'setText7',
        'text8' => 'setText8',
        'text9' => 'setText9',
        'text10' => 'setText10',
        'date1' => 'setDate1',
        'date2' => 'setDate2',
        'date3' => 'setDate3',
        'date4' => 'setDate4',
        'date5' => 'setDate5',
        'bool1' => 'setBool1',
        'bool2' => 'setBool2',
        'bool3' => 'setBool3',
        'bool4' => 'setBool4',
        'bool5' => 'setBool5'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hierarchy_name' => 'getHierarchyName',
        'type' => 'getType',
        'hierarchy_id' => 'getHierarchyId',
        'person_category_id_internal' => 'getPersonCategoryIdInternal',
        'street' => 'getStreet',
        'po_box' => 'getPoBox',
        'zip' => 'getZip',
        'city' => 'getCity',
        'country' => 'getCountry',
        'phone' => 'getPhone',
        'fax' => 'getFax',
        'e_mail' => 'getEMail',
        'commentary' => 'getCommentary',
        'text1' => 'getText1',
        'text2' => 'getText2',
        'text3' => 'getText3',
        'text4' => 'getText4',
        'text5' => 'getText5',
        'text6' => 'getText6',
        'text7' => 'getText7',
        'text8' => 'getText8',
        'text9' => 'getText9',
        'text10' => 'getText10',
        'date1' => 'getDate1',
        'date2' => 'getDate2',
        'date3' => 'getDate3',
        'date4' => 'getDate4',
        'date5' => 'getDate5',
        'bool1' => 'getBool1',
        'bool2' => 'getBool2',
        'bool3' => 'getBool3',
        'bool4' => 'getBool4',
        'bool5' => 'getBool5'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('hierarchy_name', $data ?? [], 'Hierarchy01');
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('hierarchy_id', $data ?? [], 'Hierarchy01');
        $this->setIfExists('person_category_id_internal', $data ?? [], 1);
        $this->setIfExists('street', $data ?? [], 'Street01');
        $this->setIfExists('po_box', $data ?? [], 'PoBox01');
        $this->setIfExists('zip', $data ?? [], 'Zip01');
        $this->setIfExists('city', $data ?? [], 'City01');
        $this->setIfExists('country', $data ?? [], 'Country01');
        $this->setIfExists('phone', $data ?? [], 'Phone01');
        $this->setIfExists('fax', $data ?? [], 'Fax01');
        $this->setIfExists('e_mail', $data ?? [], 'EMail01');
        $this->setIfExists('commentary', $data ?? [], 'Commentary01');
        $this->setIfExists('text1', $data ?? [], 'Text1');
        $this->setIfExists('text2', $data ?? [], 'Text2');
        $this->setIfExists('text3', $data ?? [], 'Text3');
        $this->setIfExists('text4', $data ?? [], 'Text4');
        $this->setIfExists('text5', $data ?? [], 'Text5');
        $this->setIfExists('text6', $data ?? [], 'Text6');
        $this->setIfExists('text7', $data ?? [], 'Text7');
        $this->setIfExists('text8', $data ?? [], 'Text8');
        $this->setIfExists('text9', $data ?? [], 'Text9');
        $this->setIfExists('text10', $data ?? [], 'Text10');
        $this->setIfExists('date1', $data ?? [], null);
        $this->setIfExists('date2', $data ?? [], null);
        $this->setIfExists('date3', $data ?? [], null);
        $this->setIfExists('date4', $data ?? [], null);
        $this->setIfExists('date5', $data ?? [], null);
        $this->setIfExists('bool1', $data ?? [], false);
        $this->setIfExists('bool2', $data ?? [], false);
        $this->setIfExists('bool3', $data ?? [], false);
        $this->setIfExists('bool4', $data ?? [], false);
        $this->setIfExists('bool5', $data ?? [], false);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['hierarchy_name'] === null) {
            $invalidProperties[] = "'hierarchy_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hierarchy_name
     *
     * @return string
     */
    public function getHierarchyName()
    {
        return $this->container['hierarchy_name'];
    }

    /**
     * Sets hierarchy_name
     *
     * @param string $hierarchy_name hierarchy_name
     *
     * @return self
     */
    public function setHierarchyName($hierarchy_name)
    {
        if (is_null($hierarchy_name)) {
            throw new \InvalidArgumentException('non-nullable hierarchy_name cannot be null');
        }
        $this->container['hierarchy_name'] = $hierarchy_name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Exos\ExosApi\Model\HierarchyType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Exos\ExosApi\Model\HierarchyType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets hierarchy_id
     *
     * @return string|null
     */
    public function getHierarchyId()
    {
        return $this->container['hierarchy_id'];
    }

    /**
     * Sets hierarchy_id
     *
     * @param string|null $hierarchy_id hierarchy_id
     *
     * @return self
     */
    public function setHierarchyId($hierarchy_id)
    {
        if (is_null($hierarchy_id)) {
            array_push($this->openAPINullablesSetToNull, 'hierarchy_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hierarchy_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hierarchy_id'] = $hierarchy_id;

        return $this;
    }

    /**
     * Gets person_category_id_internal
     *
     * @return int|null
     */
    public function getPersonCategoryIdInternal()
    {
        return $this->container['person_category_id_internal'];
    }

    /**
     * Sets person_category_id_internal
     *
     * @param int|null $person_category_id_internal person_category_id_internal
     *
     * @return self
     */
    public function setPersonCategoryIdInternal($person_category_id_internal)
    {
        if (is_null($person_category_id_internal)) {
            array_push($this->openAPINullablesSetToNull, 'person_category_id_internal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('person_category_id_internal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['person_category_id_internal'] = $person_category_id_internal;

        return $this;
    }

    /**
     * Gets street
     *
     * @return string|null
     */
    public function getStreet()
    {
        return $this->container['street'];
    }

    /**
     * Sets street
     *
     * @param string|null $street street
     *
     * @return self
     */
    public function setStreet($street)
    {
        if (is_null($street)) {
            array_push($this->openAPINullablesSetToNull, 'street');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('street', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['street'] = $street;

        return $this;
    }

    /**
     * Gets po_box
     *
     * @return string|null
     */
    public function getPoBox()
    {
        return $this->container['po_box'];
    }

    /**
     * Sets po_box
     *
     * @param string|null $po_box po_box
     *
     * @return self
     */
    public function setPoBox($po_box)
    {
        if (is_null($po_box)) {
            array_push($this->openAPINullablesSetToNull, 'po_box');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('po_box', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['po_box'] = $po_box;

        return $this;
    }

    /**
     * Gets zip
     *
     * @return string|null
     */
    public function getZip()
    {
        return $this->container['zip'];
    }

    /**
     * Sets zip
     *
     * @param string|null $zip zip
     *
     * @return self
     */
    public function setZip($zip)
    {
        if (is_null($zip)) {
            array_push($this->openAPINullablesSetToNull, 'zip');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('zip', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['zip'] = $zip;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            array_push($this->openAPINullablesSetToNull, 'city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            array_push($this->openAPINullablesSetToNull, 'country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return string|null
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param string|null $fax fax
     *
     * @return self
     */
    public function setFax($fax)
    {
        if (is_null($fax)) {
            array_push($this->openAPINullablesSetToNull, 'fax');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fax', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets e_mail
     *
     * @return string|null
     */
    public function getEMail()
    {
        return $this->container['e_mail'];
    }

    /**
     * Sets e_mail
     *
     * @param string|null $e_mail e_mail
     *
     * @return self
     */
    public function setEMail($e_mail)
    {
        if (is_null($e_mail)) {
            array_push($this->openAPINullablesSetToNull, 'e_mail');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('e_mail', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['e_mail'] = $e_mail;

        return $this;
    }

    /**
     * Gets commentary
     *
     * @return string|null
     */
    public function getCommentary()
    {
        return $this->container['commentary'];
    }

    /**
     * Sets commentary
     *
     * @param string|null $commentary commentary
     *
     * @return self
     */
    public function setCommentary($commentary)
    {
        if (is_null($commentary)) {
            array_push($this->openAPINullablesSetToNull, 'commentary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('commentary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['commentary'] = $commentary;

        return $this;
    }

    /**
     * Gets text1
     *
     * @return string|null
     */
    public function getText1()
    {
        return $this->container['text1'];
    }

    /**
     * Sets text1
     *
     * @param string|null $text1 text1
     *
     * @return self
     */
    public function setText1($text1)
    {
        if (is_null($text1)) {
            array_push($this->openAPINullablesSetToNull, 'text1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text1'] = $text1;

        return $this;
    }

    /**
     * Gets text2
     *
     * @return string|null
     */
    public function getText2()
    {
        return $this->container['text2'];
    }

    /**
     * Sets text2
     *
     * @param string|null $text2 text2
     *
     * @return self
     */
    public function setText2($text2)
    {
        if (is_null($text2)) {
            array_push($this->openAPINullablesSetToNull, 'text2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text2'] = $text2;

        return $this;
    }

    /**
     * Gets text3
     *
     * @return string|null
     */
    public function getText3()
    {
        return $this->container['text3'];
    }

    /**
     * Sets text3
     *
     * @param string|null $text3 text3
     *
     * @return self
     */
    public function setText3($text3)
    {
        if (is_null($text3)) {
            array_push($this->openAPINullablesSetToNull, 'text3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text3'] = $text3;

        return $this;
    }

    /**
     * Gets text4
     *
     * @return string|null
     */
    public function getText4()
    {
        return $this->container['text4'];
    }

    /**
     * Sets text4
     *
     * @param string|null $text4 text4
     *
     * @return self
     */
    public function setText4($text4)
    {
        if (is_null($text4)) {
            array_push($this->openAPINullablesSetToNull, 'text4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text4'] = $text4;

        return $this;
    }

    /**
     * Gets text5
     *
     * @return string|null
     */
    public function getText5()
    {
        return $this->container['text5'];
    }

    /**
     * Sets text5
     *
     * @param string|null $text5 text5
     *
     * @return self
     */
    public function setText5($text5)
    {
        if (is_null($text5)) {
            array_push($this->openAPINullablesSetToNull, 'text5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text5'] = $text5;

        return $this;
    }

    /**
     * Gets text6
     *
     * @return string|null
     */
    public function getText6()
    {
        return $this->container['text6'];
    }

    /**
     * Sets text6
     *
     * @param string|null $text6 text6
     *
     * @return self
     */
    public function setText6($text6)
    {
        if (is_null($text6)) {
            array_push($this->openAPINullablesSetToNull, 'text6');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text6', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text6'] = $text6;

        return $this;
    }

    /**
     * Gets text7
     *
     * @return string|null
     */
    public function getText7()
    {
        return $this->container['text7'];
    }

    /**
     * Sets text7
     *
     * @param string|null $text7 text7
     *
     * @return self
     */
    public function setText7($text7)
    {
        if (is_null($text7)) {
            array_push($this->openAPINullablesSetToNull, 'text7');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text7', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text7'] = $text7;

        return $this;
    }

    /**
     * Gets text8
     *
     * @return string|null
     */
    public function getText8()
    {
        return $this->container['text8'];
    }

    /**
     * Sets text8
     *
     * @param string|null $text8 text8
     *
     * @return self
     */
    public function setText8($text8)
    {
        if (is_null($text8)) {
            array_push($this->openAPINullablesSetToNull, 'text8');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text8', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text8'] = $text8;

        return $this;
    }

    /**
     * Gets text9
     *
     * @return string|null
     */
    public function getText9()
    {
        return $this->container['text9'];
    }

    /**
     * Sets text9
     *
     * @param string|null $text9 text9
     *
     * @return self
     */
    public function setText9($text9)
    {
        if (is_null($text9)) {
            array_push($this->openAPINullablesSetToNull, 'text9');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text9', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text9'] = $text9;

        return $this;
    }

    /**
     * Gets text10
     *
     * @return string|null
     */
    public function getText10()
    {
        return $this->container['text10'];
    }

    /**
     * Sets text10
     *
     * @param string|null $text10 text10
     *
     * @return self
     */
    public function setText10($text10)
    {
        if (is_null($text10)) {
            array_push($this->openAPINullablesSetToNull, 'text10');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text10', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text10'] = $text10;

        return $this;
    }

    /**
     * Gets date1
     *
     * @return \DateTime|null
     */
    public function getDate1()
    {
        return $this->container['date1'];
    }

    /**
     * Sets date1
     *
     * @param \DateTime|null $date1 date1
     *
     * @return self
     */
    public function setDate1($date1)
    {
        if (is_null($date1)) {
            array_push($this->openAPINullablesSetToNull, 'date1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date1'] = $date1;

        return $this;
    }

    /**
     * Gets date2
     *
     * @return \DateTime|null
     */
    public function getDate2()
    {
        return $this->container['date2'];
    }

    /**
     * Sets date2
     *
     * @param \DateTime|null $date2 date2
     *
     * @return self
     */
    public function setDate2($date2)
    {
        if (is_null($date2)) {
            array_push($this->openAPINullablesSetToNull, 'date2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date2'] = $date2;

        return $this;
    }

    /**
     * Gets date3
     *
     * @return \DateTime|null
     */
    public function getDate3()
    {
        return $this->container['date3'];
    }

    /**
     * Sets date3
     *
     * @param \DateTime|null $date3 date3
     *
     * @return self
     */
    public function setDate3($date3)
    {
        if (is_null($date3)) {
            array_push($this->openAPINullablesSetToNull, 'date3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date3'] = $date3;

        return $this;
    }

    /**
     * Gets date4
     *
     * @return \DateTime|null
     */
    public function getDate4()
    {
        return $this->container['date4'];
    }

    /**
     * Sets date4
     *
     * @param \DateTime|null $date4 date4
     *
     * @return self
     */
    public function setDate4($date4)
    {
        if (is_null($date4)) {
            array_push($this->openAPINullablesSetToNull, 'date4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date4'] = $date4;

        return $this;
    }

    /**
     * Gets date5
     *
     * @return \DateTime|null
     */
    public function getDate5()
    {
        return $this->container['date5'];
    }

    /**
     * Sets date5
     *
     * @param \DateTime|null $date5 date5
     *
     * @return self
     */
    public function setDate5($date5)
    {
        if (is_null($date5)) {
            array_push($this->openAPINullablesSetToNull, 'date5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date5'] = $date5;

        return $this;
    }

    /**
     * Gets bool1
     *
     * @return bool|null
     */
    public function getBool1()
    {
        return $this->container['bool1'];
    }

    /**
     * Sets bool1
     *
     * @param bool|null $bool1 bool1
     *
     * @return self
     */
    public function setBool1($bool1)
    {
        if (is_null($bool1)) {
            array_push($this->openAPINullablesSetToNull, 'bool1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool1'] = $bool1;

        return $this;
    }

    /**
     * Gets bool2
     *
     * @return bool|null
     */
    public function getBool2()
    {
        return $this->container['bool2'];
    }

    /**
     * Sets bool2
     *
     * @param bool|null $bool2 bool2
     *
     * @return self
     */
    public function setBool2($bool2)
    {
        if (is_null($bool2)) {
            array_push($this->openAPINullablesSetToNull, 'bool2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool2'] = $bool2;

        return $this;
    }

    /**
     * Gets bool3
     *
     * @return bool|null
     */
    public function getBool3()
    {
        return $this->container['bool3'];
    }

    /**
     * Sets bool3
     *
     * @param bool|null $bool3 bool3
     *
     * @return self
     */
    public function setBool3($bool3)
    {
        if (is_null($bool3)) {
            array_push($this->openAPINullablesSetToNull, 'bool3');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool3', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool3'] = $bool3;

        return $this;
    }

    /**
     * Gets bool4
     *
     * @return bool|null
     */
    public function getBool4()
    {
        return $this->container['bool4'];
    }

    /**
     * Sets bool4
     *
     * @param bool|null $bool4 bool4
     *
     * @return self
     */
    public function setBool4($bool4)
    {
        if (is_null($bool4)) {
            array_push($this->openAPINullablesSetToNull, 'bool4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool4'] = $bool4;

        return $this;
    }

    /**
     * Gets bool5
     *
     * @return bool|null
     */
    public function getBool5()
    {
        return $this->container['bool5'];
    }

    /**
     * Sets bool5
     *
     * @param bool|null $bool5 bool5
     *
     * @return self
     */
    public function setBool5($bool5)
    {
        if (is_null($bool5)) {
            array_push($this->openAPINullablesSetToNull, 'bool5');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bool5', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bool5'] = $bool5;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


